package thuvien.client.view;

import java.awt.Frame;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import thuvien.client.controller.ClientAuthController;
import thuvien.client.network.NetworkClient;
import thuvien.client.view.common.AsyncWorker;

/**
 * Dialog for authenticated users to change their password securely.
 */
public class ChangePasswordDialog extends JDialog {
    private final ClientAuthController authController;

    public ChangePasswordDialog(Frame parent, NetworkClient networkClient) {
        super(parent, true);
        this.authController = new ClientAuthController(networkClient);
        initComponents();
        initCustom();
    }

    private void initCustom() {
        ((javax.swing.JComponent) getContentPane()).setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        setSize(400, 260);
        setLocationRelativeTo(getParent());
        getRootPane().setDefaultButton(saveButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        formPanel = new javax.swing.JPanel();
        lblCurrentPassword = new javax.swing.JLabel();
        currentPasswordField = new javax.swing.JPasswordField();
        lblNewPassword = new javax.swing.JLabel();
        newPasswordField = new javax.swing.JPasswordField();
        lblConfirmPassword = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        bottomPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        btnPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đổi Mật Khẩu");
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 15));

        formPanel.setLayout(new java.awt.GridBagLayout());

        lblCurrentPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCurrentPassword.setText("Mật khẩu hiện tại:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(lblCurrentPassword, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(currentPasswordField, gridBagConstraints);

        lblNewPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNewPassword.setText("Mật khẩu mới:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(lblNewPassword, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(newPasswordField, gridBagConstraints);

        lblConfirmPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblConfirmPassword.setText("Xác nhận mật khẩu:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(lblConfirmPassword, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(confirmPasswordField, gridBagConstraints);

        getContentPane().add(formPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setLayout(new java.awt.BorderLayout(5, 8));

        statusLabel.setForeground(new java.awt.Color(100, 100, 100));
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("Mật khẩu mới phải có ít nhất 6 ký tự.");
        bottomPanel.add(statusLabel, java.awt.BorderLayout.NORTH);

        btnPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 0));

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saveButton.setText("Lưu thay đổi");
        saveButton.setPreferredSize(new java.awt.Dimension(120, 32));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        btnPanel.add(saveButton);

        cancelButton.setText("Hủy bỏ");
        cancelButton.setPreferredSize(new java.awt.Dimension(90, 32));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        btnPanel.add(cancelButton);

        bottomPanel.add(btnPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        performChangePassword();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void performChangePassword() {
        String currentPass = new String(currentPasswordField.getPassword());
        String newPass = new String(newPasswordField.getPassword());
        String confirmPass = new String(confirmPasswordField.getPassword());

        if (currentPass.isEmpty() || newPass.isEmpty() || confirmPass.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Vui lòng nhập đầy đủ các trường thông tin.",
                    "Lỗi Nhập Liệu",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (newPass.length() < 6) {
            JOptionPane.showMessageDialog(this,
                    "Mật khẩu mới phải có tối thiểu 6 ký tự.",
                    "Mật Khẩu Không Hợp Lệ",
                    JOptionPane.WARNING_MESSAGE);
            newPasswordField.requestFocusInWindow();
            return;
        }

        if (!newPass.equals(confirmPass)) {
            JOptionPane.showMessageDialog(this,
                    "Mật khẩu mới và xác nhận mật khẩu không trùng khớp.",
                    "Lỗi Khớp Mật Khẩu",
                    JOptionPane.WARNING_MESSAGE);
            confirmPasswordField.requestFocusInWindow();
            return;
        }

        saveButton.setEnabled(false);
        cancelButton.setEnabled(false);
        statusLabel.setText("Đang gửi yêu cầu đổi mật khẩu...");

        AsyncWorker.run(
                () -> authController.changePassword(currentPass, newPass),
                (Boolean success) -> {
                    JOptionPane.showMessageDialog(this,
                            "Đổi mật khẩu thành công!",
                            "Thông Báo",
                            JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                },
                (Exception ex) -> {
                    saveButton.setEnabled(true);
                    cancelButton.setEnabled(true);
                    statusLabel.setText("Đổi mật khẩu thất bại.");
                    String msg = ex.getMessage() != null && !ex.getMessage().isEmpty()
                            ? ex.getMessage()
                            : "Không thể đổi mật khẩu.";
                    JOptionPane.showMessageDialog(this, msg, "Lỗi Đổi Mật Khẩu", JOptionPane.ERROR_MESSAGE);
                }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JPasswordField currentPasswordField;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblCurrentPassword;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
