package thuvien.client.view;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import thuvien.client.controller.ClientAuthController;
import thuvien.client.network.NetworkClient;
import thuvien.client.network.RMIClient;
import thuvien.client.view.common.AsyncWorker;
import thuvien.common.dto.UserSessionDTO;
import thuvien.common.exception.AuthenticationException;
import thuvien.common.exception.NetworkException;

/**
 * Authentication dialog / window for the Remote School Library client.
 * Connects to the server over Java RMI, handles login, and displays user-friendly status and errors.
 */
public class LoginForm extends JFrame {
    private static final Logger LOGGER = Logger.getLogger(LoginForm.class.getName());

    private final NetworkClient networkClient;
    private final ClientAuthController authController;

    public LoginForm() {
        this(new RMIClient());
    }

    public LoginForm(NetworkClient networkClient) {
        this.networkClient = networkClient;
        this.authController = new ClientAuthController(networkClient);
        initComponents();
        initCustom();
    }

    private void initCustom() {
        setSize(480, 440);
        setLocationRelativeTo(null);
        getRootPane().setBorder(BorderFactory.createEmptyBorder(18, 25, 18, 25));

        if (networkClient != null) {
            serverHostField.setText(networkClient.getHost());
            serverPortField.setText(String.valueOf(networkClient.getPort()));
        }

        getRootPane().setDefaultButton(loginButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        subHeaderLabel = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        hostLabel = new javax.swing.JLabel();
        serverHostField = new javax.swing.JTextField();
        portLabel = new javax.swing.JLabel();
        serverPortField = new javax.swing.JTextField();
        testConnectionButton = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        bottomPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        loginRow = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        regRow = new javax.swing.JPanel();
        registerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ Thống Quản Lý Thư Viện - Đăng Nhập");
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 12));

        headerPanel.setOpaque(false);
        headerPanel.setLayout(new java.awt.BorderLayout(0, 4));

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Quản Lý Thư Viện Trường Học");
        headerPanel.add(headerLabel, java.awt.BorderLayout.NORTH);

        subHeaderLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        subHeaderLabel.setForeground(new java.awt.Color(100, 100, 100));
        subHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subHeaderLabel.setText("Ũng Dụng Khách Kết Nối Java RMI");
        headerPanel.add(subHeaderLabel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(headerPanel, java.awt.BorderLayout.NORTH);

        formPanel.setOpaque(false);
        formPanel.setLayout(new java.awt.GridBagLayout());

        hostLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hostLabel.setText("Server IP:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 5, 6);
        formPanel.add(hostLabel, gridBagConstraints);

        serverHostField.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 5, 6);
        formPanel.add(serverHostField, gridBagConstraints);

        portLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        portLabel.setText("Port:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 5, 6);
        formPanel.add(portLabel, gridBagConstraints);

        serverPortField.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 5, 6);
        formPanel.add(serverPortField, gridBagConstraints);

        testConnectionButton.setText("Kiểm tra kết nối");
        testConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testConnectionButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 5, 6);
        formPanel.add(testConnectionButton, gridBagConstraints);

        userLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userLabel.setText("Tên đăng nhập:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 5, 6);
        formPanel.add(userLabel, gridBagConstraints);

        usernameField.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 5, 6);
        formPanel.add(usernameField, gridBagConstraints);

        passLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passLabel.setText("Mật khẩu:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 5, 6);
        formPanel.add(passLabel, gridBagConstraints);

        passwordField.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 5, 6);
        formPanel.add(passwordField, gridBagConstraints);

        getContentPane().add(formPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setOpaque(false);
        bottomPanel.setLayout(new java.awt.BorderLayout(5, 8));

        statusLabel.setForeground(new java.awt.Color(80, 80, 80));
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("Vui lòng nhập tài khoản và mật khẩu.");
        bottomPanel.add(statusLabel, java.awt.BorderLayout.NORTH);

        buttonPanel.setOpaque(false);
        buttonPanel.setLayout(new java.awt.BorderLayout(0, 8));

        loginRow.setOpaque(false);

        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginButton.setText("Đăng nhập");
        loginButton.setPreferredSize(new java.awt.Dimension(140, 32));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginRow.add(loginButton);

        buttonPanel.add(loginRow, java.awt.BorderLayout.NORTH);

        regRow.setOpaque(false);

        registerButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        registerButton.setForeground(new java.awt.Color(30, 80, 160));
        registerButton.setText("Chưa có tài khoản? Đăng ký tại đây");
        registerButton.setBorderPainted(false);
        registerButton.setContentAreaFilled(false);
        registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerButton.setFocusPainted(false);
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        regRow.add(registerButton);

        buttonPanel.add(regRow, java.awt.BorderLayout.SOUTH);

        bottomPanel.add(buttonPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void testConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testConnectionButtonActionPerformed
        performTestConnection();
    }//GEN-LAST:event_testConnectionButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        performLogin();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        if (!applyServerSettingsFromUI()) {
            return;
        }
        StudentRegistrationDialog dialog = new StudentRegistrationDialog(this, networkClient);
        dialog.setVisible(true);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void setInputsEnabled(boolean enabled) {
        serverHostField.setEnabled(enabled);
        serverPortField.setEnabled(enabled);
        testConnectionButton.setEnabled(enabled);
        usernameField.setEnabled(enabled);
        passwordField.setEnabled(enabled);
        loginButton.setEnabled(enabled);
        registerButton.setEnabled(enabled);
    }

    private boolean applyServerSettingsFromUI() {
        String host = serverHostField.getText().trim();
        String portStr = serverPortField.getText().trim();
        if (host.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Vui lòng nhập địa chỉ Server IP.",
                    "Lỗi Cấu Hình",
                    JOptionPane.WARNING_MESSAGE);
            serverHostField.requestFocusInWindow();
            return false;
        }
        int port;
        try {
            port = Integer.parseInt(portStr);
            if (port < 1 || port > 65535) {
                throw new NumberFormatException("Out of range");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Port phải là số nguyên hợp lệ (1 - 65535).",
                    "Lỗi Cấu Hình",
                    JOptionPane.WARNING_MESSAGE);
            serverPortField.requestFocusInWindow();
            return false;
        }
        networkClient.setServerAddress(host, port);
        return true;
    }

    private void performTestConnection() {
        if (!applyServerSettingsFromUI()) {
            return;
        }
        final String host = networkClient.getHost();
        final int port = networkClient.getPort();

        setInputsEnabled(false);
        statusLabel.setForeground(new Color(80, 80, 80));
        statusLabel.setText("Đang kiểm tra kết nối tới " + host + ":" + port + "...");

        AsyncWorker.run(
                () -> {
                    networkClient.connect(host, port);
                    return networkClient.ping();
                },
                (Boolean pongOk) -> {
                    setInputsEnabled(true);
                    if (Boolean.TRUE.equals(pongOk)) {
                        statusLabel.setForeground(new Color(20, 130, 50));
                        statusLabel.setText("Server connected");
                        JOptionPane.showMessageDialog(LoginForm.this,
                                "Server connected",
                                "Kết Nối Thành Công",
                                JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        statusLabel.setForeground(new Color(180, 40, 40));
                        statusLabel.setText("Cannot connect to server");
                        JOptionPane.showMessageDialog(LoginForm.this,
                                "Cannot connect to server",
                                "Lỗi Kết Nối",
                                JOptionPane.ERROR_MESSAGE);
                    }
                },
                (Exception ex) -> {
                    setInputsEnabled(true);
                    statusLabel.setForeground(new Color(180, 40, 40));
                    String errorMsg = (ex.getMessage() != null && !ex.getMessage().trim().isEmpty())
                            ? ex.getMessage()
                            : "Cannot connect to server";
                    JOptionPane.showMessageDialog(LoginForm.this,
                            errorMsg,
                            "Lỗi Kết Nối RMI",
                            JOptionPane.ERROR_MESSAGE);
                }
        );
    }

    private void performLogin() {
        if (!applyServerSettingsFromUI()) {
            return;
        }
        String username = usernameField.getText().trim();
        char[] passChars = passwordField.getPassword();
        String password = new String(passChars);

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Vui lòng nhập đầy đủ tên đăng nhập và mật khẩu.",
                    "Lỗi Nhập Liệu",
                    JOptionPane.WARNING_MESSAGE);
            if (username.isEmpty()) {
                usernameField.requestFocusInWindow();
            } else {
                passwordField.requestFocusInWindow();
            }
            return;
        }

        // Disable inputs and show loading state
        setInputsEnabled(false);
        statusLabel.setForeground(new Color(80, 80, 80));
        statusLabel.setText("Đang kết nối và xác thực với máy chủ...");

        // Non-blocking network call via AsyncWorker off the EDT
        AsyncWorker.run(
                () -> authController.login(username, password),
                (UserSessionDTO session) -> {
                    statusLabel.setText("Đăng nhập thành công.");
                    dispose();
                    SwingUtilities.invokeLater(() -> new MainDashboardForm(networkClient, session).setVisible(true));
                },
                (Exception ex) -> {
                    // Re-enable inputs on failure
                    setInputsEnabled(true);
                    passwordField.setText("");
                    passwordField.requestFocusInWindow();

                    String errorTitle;
                    String errorMsg;

                    if (ex instanceof AuthenticationException) {
                        errorTitle = "Đăng Nhập Thất Bại";
                        errorMsg = (ex.getMessage() != null && !ex.getMessage().isEmpty())
                                ? ex.getMessage()
                                : "Tên đăng nhập hoặc mật khẩu không chính xác.";
                        statusLabel.setText(errorMsg);
                    } else if (ex instanceof NetworkException) {
                        errorTitle = "Lỗi Kết Nối Máy Chủ";
                        errorMsg = "Cannot connect to server (" + networkClient.getHost() + ":" + networkClient.getPort() + ").\n"
                                + "Vui lòng kiểm tra lại Server IP, Port và kết nối mạng.";
                        statusLabel.setText("Cannot connect to server");
                        LOGGER.log(Level.WARNING, "Login network failure", ex);
                    } else {
                        errorTitle = "Lỗi Hệ Thống";
                        errorMsg = "Đã xảy ra lỗi trong quá trình xác thực.";
                        statusLabel.setText("Lỗi hệ thống khi đăng nhập.");
                        LOGGER.log(Level.SEVERE, "Unexpected login error", ex);
                    }

                    JOptionPane.showMessageDialog(LoginForm.this, errorMsg, errorTitle, JOptionPane.ERROR_MESSAGE);
                }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel hostLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginRow;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel portLabel;
    private javax.swing.JPanel regRow;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField serverHostField;
    private javax.swing.JTextField serverPortField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel subHeaderLabel;
    private javax.swing.JButton testConnectionButton;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
