package thuvien.client.view;

import java.awt.Frame;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import thuvien.client.controller.ClientAuthController;
import thuvien.client.network.NetworkClient;
import thuvien.client.view.common.AsyncWorker;
import thuvien.common.dto.RegisterStudentRequestDTO;

/**
 * Dialog for student self-registration using cryptographic activation codes issued by Admin.
 */
public class StudentRegistrationDialog extends JDialog {
    private final ClientAuthController authController;

    public StudentRegistrationDialog(Frame parent, NetworkClient networkClient) {
        super(parent, true);
        this.authController = new ClientAuthController(networkClient);
        initComponents();
        initCustom();
    }

    private void initCustom() {
        ((javax.swing.JComponent) getContentPane()).setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        setSize(480, 480);
        setLocationRelativeTo(getParent());
        getRootPane().setDefaultButton(registerButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        subLabel = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        lblStudentCode = new javax.swing.JLabel();
        studentCodeField = new javax.swing.JTextField();
        lblFullName = new javax.swing.JLabel();
        fullNameField = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        lblConfirmPassword = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        lblActivationCode = new javax.swing.JLabel();
        activationCodeField = new javax.swing.JTextField();
        bottomPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        btnPanel = new javax.swing.JPanel();
        registerButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đăng Ký Tài Khoản Sinh Viên");
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 15));

        headerPanel.setLayout(new java.awt.BorderLayout(0, 4));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Đăng Ký Tài Khoản Thư Viện");
        headerPanel.add(titleLabel, java.awt.BorderLayout.NORTH);

        subLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        subLabel.setForeground(new java.awt.Color(100, 100, 100));
        subLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subLabel.setText("Dành cho sinh viên đã có hồ sơ và được cấp mã kích hoạt");
        headerPanel.add(subLabel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(headerPanel, java.awt.BorderLayout.NORTH);

        formPanel.setLayout(new java.awt.GridBagLayout());

        lblStudentCode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblStudentCode.setText("Mã sinh viên (*):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(lblStudentCode, gridBagConstraints);

        studentCodeField.setToolTipText("VD: STU002");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(studentCodeField, gridBagConstraints);

        lblFullName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFullName.setText("Họ và tên (*):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(lblFullName, gridBagConstraints);

        fullNameField.setToolTipText("VD: Nguyễn Văn A");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(fullNameField, gridBagConstraints);

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEmail.setText("Email liên hệ:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(lblEmail, gridBagConstraints);

        emailField.setToolTipText("VD: a.nguyen@student.school.edu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(emailField, gridBagConstraints);

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsername.setText("Tên đăng nhập (*):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(lblUsername, gridBagConstraints);

        usernameField.setToolTipText("VD: nguyenvana");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(usernameField, gridBagConstraints);

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPassword.setText("Mật khẩu (*):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(lblPassword, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(passwordField, gridBagConstraints);

        lblConfirmPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblConfirmPassword.setText("Xác nhận mật khẩu (*):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(lblConfirmPassword, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(confirmPasswordField, gridBagConstraints);

        lblActivationCode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblActivationCode.setText("Mã kích hoạt (*):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(lblActivationCode, gridBagConstraints);

        activationCodeField.setToolTipText("VD: ACT-XXXXXXXX");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(activationCodeField, gridBagConstraints);

        getContentPane().add(formPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setLayout(new java.awt.BorderLayout(5, 8));

        statusLabel.setForeground(new java.awt.Color(100, 100, 100));
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("(*) Các trường bắt buộc nhập");
        bottomPanel.add(statusLabel, java.awt.BorderLayout.NORTH);

        btnPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 0));

        registerButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        registerButton.setText("Đăng ký");
        registerButton.setPreferredSize(new java.awt.Dimension(110, 32));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        btnPanel.add(registerButton);

        cancelButton.setText("Hủy bỏ");
        cancelButton.setPreferredSize(new java.awt.Dimension(90, 32));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        btnPanel.add(cancelButton);

        bottomPanel.add(btnPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        performRegister();
    }//GEN-LAST:event_registerButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void performRegister() {
        String studentCode = studentCodeField.getText().trim();
        String fullName = fullNameField.getText().trim();
        String email = emailField.getText().trim();
        String username = usernameField.getText().trim();
        String password = new String(passwordField.getPassword());
        String confirmPassword = new String(confirmPasswordField.getPassword());
        String activationCode = activationCodeField.getText().trim();

        if (studentCode.isEmpty() || fullName.isEmpty() || username.isEmpty() || password.isEmpty() || activationCode.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Vui lòng điền đầy đủ các thông tin bắt buộc (*).",
                    "Thiếu Thông Tin",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (password.length() < 6) {
            JOptionPane.showMessageDialog(this,
                    "Mật khẩu phải có độ dài tối thiểu 6 ký tự.",
                    "Mật Khẩu Quá Ngắn",
                    JOptionPane.WARNING_MESSAGE);
            passwordField.requestFocusInWindow();
            return;
        }

        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this,
                    "Mật khẩu xác nhận không khớp.",
                    "Lỗi Xác Nhận Mật Khẩu",
                    JOptionPane.WARNING_MESSAGE);
            confirmPasswordField.requestFocusInWindow();
            return;
        }

        RegisterStudentRequestDTO request = new RegisterStudentRequestDTO(
                studentCode, fullName, email, username, password, confirmPassword, activationCode);

        registerButton.setEnabled(false);
        cancelButton.setEnabled(false);
        statusLabel.setText("Đang xử lý đăng ký với máy chủ...");

        AsyncWorker.run(
                () -> authController.registerStudent(request),
                (Boolean success) -> {
                    JOptionPane.showMessageDialog(this,
                            "Chúc mừng! Bạn đã đăng ký tài khoản thành công.\n"
                            + "Tên đăng nhập: " + username + "\n"
                            + "Bây giờ bạn có thể đăng nhập vào hệ thống.",
                            "Đăng Ký Thành Công",
                            JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                },
                (Exception ex) -> {
                    registerButton.setEnabled(true);
                    cancelButton.setEnabled(true);
                    statusLabel.setText("Đăng ký thất bại.");
                    String msg = ex.getMessage() != null && !ex.getMessage().isEmpty()
                            ? ex.getMessage()
                            : "Đã xảy ra lỗi trong quá trình đăng ký.";
                    JOptionPane.showMessageDialog(this, msg, "Lỗi Đăng Ký", JOptionPane.ERROR_MESSAGE);
                }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField activationCodeField;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JTextField emailField;
    private javax.swing.JPanel formPanel;
    private javax.swing.JTextField fullNameField;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel lblActivationCode;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblStudentCode;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField studentCodeField;
    private javax.swing.JLabel subLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
