package thuvien.client.view.dialogs;

import java.awt.Window;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import thuvien.client.controller.ClientBookController;
import thuvien.client.network.NetworkClient;
import thuvien.client.view.common.AsyncWorker;
import thuvien.common.dto.BookDTO;
import thuvien.common.dto.CategoryDTO;
import thuvien.common.enums.BookStatus;

/**
 * Modal dialog for creating and editing Book entries.
 */
public class BookFormDialog extends JDialog {
    private final ClientBookController bookController;
    private final BookDTO bookToEdit;
    private boolean saved = false;

    public BookFormDialog(Window owner, NetworkClient networkClient, BookDTO bookToEdit) {
        super(owner, ModalityType.APPLICATION_MODAL);
        this.bookController = new ClientBookController(networkClient);
        this.bookToEdit = bookToEdit;

        initComponents();
        initCustom();
        loadCategories();
    }

    private void initCustom() {
        setTitle(bookToEdit == null ? "Thêm Sách Mới" : "Chỉnh Sửa Sách (ID: " + bookToEdit.getId() + ")");
        ((javax.swing.JComponent) getContentPane()).setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        setSize(560, 540);
        setLocationRelativeTo(getOwner());
        getRootPane().setDefaultButton(saveButton);

        if (bookToEdit != null) {
            titleField.setText(bookToEdit.getTitle());
            isbnField.setText(bookToEdit.getIsbn());
            publisherField.setText(bookToEdit.getPublisher() != null ? bookToEdit.getPublisher() : "");
            if (bookToEdit.getPublishYear() != null) {
                yearSpinner.setValue(bookToEdit.getPublishYear());
            }
            editionField.setText(bookToEdit.getEdition() != null ? bookToEdit.getEdition() : "");
            totalCopiesSpinner.setValue(bookToEdit.getTotalCopies());
            availableCopiesSpinner.setValue(bookToEdit.getAvailableCopies());
            shelfLocationField.setText(bookToEdit.getShelfLocation() != null ? bookToEdit.getShelfLocation() : "");
            if (bookToEdit.getStatus() != null) {
                statusCombo.setSelectedItem(bookToEdit.getStatus());
            }
            saveButton.setText("Lưu Thay Đổi");
        } else {
            statusCombo.setSelectedItem(BookStatus.AVAILABLE);
            saveButton.setText("Tạo Sách Mới");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        formPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        lblIsbn = new javax.swing.JLabel();
        isbnField = new javax.swing.JTextField();
        lblCategory = new javax.swing.JLabel();
        catPanel = new javax.swing.JPanel();
        categoryCombo = new javax.swing.JComboBox<CategoryDTO>();
        retryCategoryBtn = new javax.swing.JButton();
        lblPublisher = new javax.swing.JLabel();
        publisherField = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        yearSpinner = new javax.swing.JSpinner();
        lblEdition = new javax.swing.JLabel();
        editionField = new javax.swing.JTextField();
        lblTotalCopies = new javax.swing.JLabel();
        totalCopiesSpinner = new javax.swing.JSpinner();
        lblAvailableCopies = new javax.swing.JLabel();
        availableCopiesSpinner = new javax.swing.JSpinner();
        lblShelfLocation = new javax.swing.JLabel();
        shelfLocationField = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        statusCombo = new javax.swing.JComboBox<BookStatus>();
        bottomPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông Tin Sách");
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        formPanel.setLayout(new java.awt.GridBagLayout());

        lblTitle.setText("Tên sách:*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(lblTitle, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(titleField, gridBagConstraints);

        lblIsbn.setText("Mã ISBN:*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(lblIsbn, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(isbnField, gridBagConstraints);

        lblCategory.setText("Thể loại:*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(lblCategory, gridBagConstraints);

        catPanel.setOpaque(false);
        catPanel.setLayout(new java.awt.BorderLayout(6, 0));

        categoryCombo.setEnabled(false);
        catPanel.add(categoryCombo, java.awt.BorderLayout.CENTER);

        retryCategoryBtn.setText("Thử lại");
        retryCategoryBtn.setToolTipText("Tải lại danh sách thể loại từ máy chủ");
        retryCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retryCategoryBtnActionPerformed(evt);
            }
        });
        catPanel.add(retryCategoryBtn, java.awt.BorderLayout.EAST);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(catPanel, gridBagConstraints);

        lblPublisher.setText("Nhà xuất bản:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(lblPublisher, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(publisherField, gridBagConstraints);

        lblYear.setText("Năm xuất bản:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(lblYear, gridBagConstraints);

        yearSpinner.setModel(new javax.swing.SpinnerNumberModel(2024, 1000, 2100, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(yearSpinner, gridBagConstraints);

        lblEdition.setText("Tái bản / Phiên bản:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(lblEdition, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(editionField, gridBagConstraints);

        lblTotalCopies.setText("Tổng số bản:*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(lblTotalCopies, gridBagConstraints);

        totalCopiesSpinner.setModel(new javax.swing.SpinnerNumberModel(5, 1, 9999, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(totalCopiesSpinner, gridBagConstraints);

        lblAvailableCopies.setText("Bản hiện có sẵn:*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(lblAvailableCopies, gridBagConstraints);

        availableCopiesSpinner.setModel(new javax.swing.SpinnerNumberModel(5, 0, 9999, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(availableCopiesSpinner, gridBagConstraints);

        lblShelfLocation.setText("Vị trí kệ:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(lblShelfLocation, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(shelfLocationField, gridBagConstraints);

        lblStatus.setText("Trạng thái:*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(lblStatus, gridBagConstraints);

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(thuvien.common.enums.BookStatus.values()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(statusCombo, gridBagConstraints);

        getContentPane().add(formPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setLayout(new java.awt.BorderLayout(5, 5));

        statusLabel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText(" ");
        bottomPanel.add(statusLabel, java.awt.BorderLayout.NORTH);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5));

        cancelButton.setText("Hủy bỏ");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saveButton.setText("Lưu Thay Đổi");
        saveButton.setPreferredSize(new java.awt.Dimension(130, 30));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(saveButton);

        bottomPanel.add(buttonPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retryCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retryCategoryBtnActionPerformed
        loadCategories();
    }//GEN-LAST:event_retryCategoryBtnActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        saveBook();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void loadCategories() {
        statusLabel.setText("Đang tải danh sách thể loại từ máy chủ...");
        if (retryCategoryBtn != null) retryCategoryBtn.setEnabled(false);
        categoryCombo.setEnabled(false);

        AsyncWorker.run(
                bookController::listCategories,
                (List<CategoryDTO> categories) -> {
                    categoryCombo.removeAllItems();
                    CategoryDTO selected = null;
                    for (CategoryDTO cat : categories) {
                        categoryCombo.addItem(cat);
                        if (bookToEdit != null && cat.getId().equals(bookToEdit.getCategoryId())) {
                            selected = cat;
                        }
                    }
                    if (selected != null) {
                        categoryCombo.setSelectedItem(selected);
                    }
                    categoryCombo.setEnabled(true);
                    if (retryCategoryBtn != null) retryCategoryBtn.setEnabled(true);
                    statusLabel.setText("Sẵn sàng");
                },
                (Exception ex) -> {
                    categoryCombo.setEnabled(false);
                    if (retryCategoryBtn != null) retryCategoryBtn.setEnabled(true);
                    statusLabel.setText("Lỗi tải thể loại: " + ex.getMessage() + " (Vui lòng bấm 'Thử lại')");
                }
        );
    }

    private void saveBook() {
        String title = titleField.getText().trim();
        String isbn = isbnField.getText().trim();
        CategoryDTO selectedCategory = (CategoryDTO) categoryCombo.getSelectedItem();

        if (title.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên sách.", "Lỗi Xác Thực", JOptionPane.WARNING_MESSAGE);
            titleField.requestFocusInWindow();
            return;
        }

        if (isbn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã ISBN.", "Lỗi Xác Thực", JOptionPane.WARNING_MESSAGE);
            isbnField.requestFocusInWindow();
            return;
        }

        if (selectedCategory == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một thể loại hợp lệ. (Nhấn 'Thử lại' nếu chưa tải được thể loại)", "Lỗi Xác Thực", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int totalCopies = (Integer) totalCopiesSpinner.getValue();
        int availableCopies = (Integer) availableCopiesSpinner.getValue();

        if (totalCopies < 0) {
            JOptionPane.showMessageDialog(this, "Tổng số bản không được âm.", "Lỗi Xác Thực", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (availableCopies > totalCopies) {
            JOptionPane.showMessageDialog(this, "Số bản có sẵn không được lớn hơn tổng số bản.", "Lỗi Xác Thực", JOptionPane.WARNING_MESSAGE);
            return;
        }

        BookDTO book = (bookToEdit != null) ? bookToEdit : new BookDTO();
        book.setTitle(title);
        book.setIsbn(isbn);
        book.setCategoryId(selectedCategory.getId());
        book.setCategoryName(selectedCategory.getName());
        book.setPublisher(publisherField.getText().trim());
        book.setPublishYear((Integer) yearSpinner.getValue());
        book.setEdition(editionField.getText().trim());
        book.setShelfLocation(shelfLocationField.getText().trim());
        book.setTotalCopies(totalCopies);
        book.setAvailableCopies(availableCopies);
        book.setStatus((BookStatus) statusCombo.getSelectedItem());

        // Set busy state
        saveButton.setEnabled(false);
        cancelButton.setEnabled(false);
        statusLabel.setText("Đang lưu sách lên máy chủ...");

        if (bookToEdit == null) {
            // Create Book
            AsyncWorker.run(
                    () -> bookController.createBook(book),
                    (Long newId) -> {
                        saved = true;
                        JOptionPane.showMessageDialog(this, "Thêm sách thành công! Mã sách (ID): " + newId, "Thành Công", JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                    },
                    (Exception ex) -> {
                        saveButton.setEnabled(true);
                        cancelButton.setEnabled(true);
                        statusLabel.setText("Lưu thất bại.");
                        JOptionPane.showMessageDialog(this, "Thêm sách thất bại: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
            );
        } else {
            // Update Book
            AsyncWorker.run(
                    () -> bookController.updateBook(book),
                    (Boolean ok) -> {
                        saved = true;
                        JOptionPane.showMessageDialog(this, "Cập nhật sách thành công!", "Thành Công", JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                    },
                    (Exception ex) -> {
                        saveButton.setEnabled(true);
                        cancelButton.setEnabled(true);
                        statusLabel.setText("Cập nhật thất bại.");
                        JOptionPane.showMessageDialog(this, "Cập nhật sách thất bại: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
            );
        }
    }

    public boolean isSaved() {
        return saved;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner availableCopiesSpinner;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel catPanel;
    private javax.swing.JComboBox<CategoryDTO> categoryCombo;
    private javax.swing.JTextField editionField;
    private javax.swing.JPanel formPanel;
    private javax.swing.JTextField isbnField;
    private javax.swing.JLabel lblAvailableCopies;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblEdition;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblPublisher;
    private javax.swing.JLabel lblShelfLocation;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalCopies;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField publisherField;
    private javax.swing.JButton retryCategoryBtn;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField shelfLocationField;
    private javax.swing.JComboBox<BookStatus> statusCombo;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField titleField;
    private javax.swing.JSpinner totalCopiesSpinner;
    private javax.swing.JSpinner yearSpinner;
    // End of variables declaration//GEN-END:variables
}
