package thuvien.client.view.dialogs;

import java.awt.Window;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import thuvien.client.controller.ClientBorrowController;
import thuvien.client.network.NetworkClient;
import thuvien.client.session.ClientSession;
import thuvien.client.view.common.AsyncWorker;
import thuvien.common.dto.BorrowRecordDTO;
import thuvien.common.dto.BorrowRequestDTO;

/**
 * Modal dialog for creating a new Borrow transaction.
 */
public class BorrowDialog extends JDialog {
    private final ClientBorrowController borrowController;
    private boolean saved = false;

    public BorrowDialog(Window owner, NetworkClient networkClient, Long defaultStudentId, Long defaultBookId) {
        super(owner, ModalityType.APPLICATION_MODAL);
        this.borrowController = new ClientBorrowController(networkClient);
        initComponents();
        initCustom(defaultStudentId, defaultBookId);
    }

    private void initCustom(Long defaultStudentId, Long defaultBookId) {
        ((javax.swing.JComponent) getContentPane()).setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        setSize(460, 330);
        setLocationRelativeTo(getOwner());
        getRootPane().setDefaultButton(submitButton);

        if (defaultStudentId != null) {
            studentIdField.setText(defaultStudentId.toString());
        }
        if (defaultBookId != null) {
            bookIdField.setText(defaultBookId.toString());
        }
        if (ClientSession.getInstance().isStudent()) {
            studentIdField.setToolTipText("Mã ID hồ sơ sinh viên của bạn");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        formPanel = new javax.swing.JPanel();
        lblStudentId = new javax.swing.JLabel();
        studentIdField = new javax.swing.JTextField();
        lblBookId = new javax.swing.JLabel();
        bookIdField = new javax.swing.JTextField();
        lblDuration = new javax.swing.JLabel();
        durationSpinner = new javax.swing.JSpinner();
        lblNotes = new javax.swing.JLabel();
        notesField = new javax.swing.JTextField();
        bottomPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lập Phiếu Mượn Sách");
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        formPanel.setLayout(new java.awt.GridBagLayout());

        lblStudentId.setText("Mã ID sinh viên:*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(lblStudentId, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(studentIdField, gridBagConstraints);

        lblBookId.setText("Mã ID sách:*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(lblBookId, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(bookIdField, gridBagConstraints);

        lblDuration.setText("Thời hạn mượn (ngày):*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(lblDuration, gridBagConstraints);

        durationSpinner.setModel(new javax.swing.SpinnerNumberModel(14, 1, 90, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(durationSpinner, gridBagConstraints);

        lblNotes.setText("Ghi chú:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(lblNotes, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(notesField, gridBagConstraints);

        getContentPane().add(formPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setLayout(new java.awt.BorderLayout(5, 5));

        statusLabel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("Nhập thông tin mượn sách.");
        bottomPanel.add(statusLabel, java.awt.BorderLayout.NORTH);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5));

        cancelButton.setText("Hủy bỏ");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        submitButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submitButton.setText("Xác Nhận Mượn");
        submitButton.setPreferredSize(new java.awt.Dimension(135, 30));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(submitButton);

        bottomPanel.add(buttonPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        performBorrow();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void performBorrow() {
        String stuStr = studentIdField.getText().trim();
        String bookStr = bookIdField.getText().trim();

        if (stuStr.isEmpty() || bookStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập cả Mã ID sinh viên và Mã ID sách.", "Lỗi Xác Thực", JOptionPane.WARNING_MESSAGE);
            return;
        }

        long studentId;
        long bookId;
        try {
            studentId = Long.parseLong(stuStr);
            bookId = Long.parseLong(bookStr);
            if (studentId <= 0 || bookId <= 0) {
                JOptionPane.showMessageDialog(this, "Mã ID phải là số nguyên dương.", "Lỗi Xác Thực", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Mã ID phải là giá trị số hợp lệ.", "Lỗi Xác Thực", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int duration = (Integer) durationSpinner.getValue();
        String notes = notesField.getText().trim();

        BorrowRequestDTO req = new BorrowRequestDTO(studentId, bookId, duration, notes);

        submitButton.setEnabled(false);
        cancelButton.setEnabled(false);
        statusLabel.setText("Đang xử lý yêu cầu mượn sách trên máy chủ...");

        AsyncWorker.run(
                () -> borrowController.borrowBook(req),
                (BorrowRecordDTO record) -> {
                    saved = true;
                    String msg = String.format("Cho mượn sách thành công!\nMã phiếu: #%d\nTên sách: %s\nSinh viên: %s\nHạn trả: %s",
                            record.getId(), record.getBookTitle(), record.getStudentName(), record.getDueDate());
                    JOptionPane.showMessageDialog(this, msg, "Thành Công", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                },
                (Exception ex) -> {
                    submitButton.setEnabled(true);
                    cancelButton.setEnabled(true);
                    statusLabel.setText("Mượn sách thất bại.");
                    JOptionPane.showMessageDialog(this, "Lập phiếu mượn thất bại: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
        );
    }

    public boolean isSaved() {
        return saved;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookIdField;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JSpinner durationSpinner;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel lblBookId;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblStudentId;
    private javax.swing.JTextField notesField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField studentIdField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
