package thuvien.client.view.dialogs;

import java.awt.Window;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import thuvien.client.controller.ClientReservationController;
import thuvien.client.network.NetworkClient;
import thuvien.client.session.ClientSession;
import thuvien.client.view.common.AsyncWorker;
import thuvien.common.dto.ReservationDTO;

/**
 * Modal dialog for reserving a book.
 */
public class ReservationDialog extends JDialog {
    private final ClientReservationController reservationController;
    private boolean saved = false;

    public ReservationDialog(Window owner, NetworkClient networkClient, Long defaultBookId, Long defaultStudentId) {
        super(owner, ModalityType.APPLICATION_MODAL);
        this.reservationController = new ClientReservationController(networkClient);
        initComponents();
        initCustom(defaultBookId, defaultStudentId);
    }

    private void initCustom(Long defaultBookId, Long defaultStudentId) {
        ((javax.swing.JComponent) getContentPane()).setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        setSize(440, 270);
        setLocationRelativeTo(getOwner());
        getRootPane().setDefaultButton(submitButton);

        if (defaultBookId != null) {
            bookIdField.setText(defaultBookId.toString());
        }

        boolean isStudent = ClientSession.getInstance().isStudent();
        if (isStudent) {
            lblStudentId.setVisible(false);
            studentIdField.setVisible(false);
        } else if (defaultStudentId != null) {
            studentIdField.setText(defaultStudentId.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        formPanel = new javax.swing.JPanel();
        lblBookId = new javax.swing.JLabel();
        bookIdField = new javax.swing.JTextField();
        lblStudentId = new javax.swing.JLabel();
        studentIdField = new javax.swing.JTextField();
        bottomPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đặt Trước Sách (Giữ Chỗ)");
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        formPanel.setLayout(new java.awt.GridBagLayout());

        lblBookId.setText("Mã ID sách:*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(lblBookId, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(bookIdField, gridBagConstraints);

        lblStudentId.setText("Mã ID sinh viên:*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(lblStudentId, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(studentIdField, gridBagConstraints);

        getContentPane().add(formPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setLayout(new java.awt.BorderLayout(5, 5));

        statusLabel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("Nhập mã ID sách để đặt trước.");
        bottomPanel.add(statusLabel, java.awt.BorderLayout.NORTH);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5));

        cancelButton.setText("Hủy bỏ");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        submitButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submitButton.setText("Xác Nhận Đặt Trước");
        submitButton.setPreferredSize(new java.awt.Dimension(160, 30));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(submitButton);

        bottomPanel.add(buttonPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        performReservation();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void performReservation() {
        String bookStr = bookIdField.getText().trim();
        if (bookStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã ID sách.", "Lỗi Xác Thực", JOptionPane.WARNING_MESSAGE);
            return;
        }

        long bookId;
        try {
            bookId = Long.parseLong(bookStr);
            if (bookId <= 0) {
                JOptionPane.showMessageDialog(this, "Mã ID sách phải là số nguyên dương.", "Lỗi Xác Thực", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mã ID sách phải là số hợp lệ.", "Lỗi Xác Thực", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Long studentId = null;
        if (!ClientSession.getInstance().isStudent()) {
            String stuStr = studentIdField.getText().trim();
            if (stuStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã ID sinh viên.", "Lỗi Xác Thực", JOptionPane.WARNING_MESSAGE);
                return;
            }
            try {
                studentId = Long.parseLong(stuStr);
                if (studentId <= 0) {
                    JOptionPane.showMessageDialog(this, "Mã ID sinh viên phải là số nguyên dương.", "Lỗi Xác Thực", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Mã ID sinh viên phải là số hợp lệ.", "Lỗi Xác Thực", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        final Long finalStudentId = studentId;
        submitButton.setEnabled(false);
        cancelButton.setEnabled(false);
        statusLabel.setText("Đang gửi yêu cầu đặt trước đến máy chủ...");

        AsyncWorker.run(
                () -> reservationController.createReservation(bookId, finalStudentId),
                (ReservationDTO r) -> {
                    saved = true;
                    String msg = String.format("Đặt trước sách thành công!\nMã đặt trước: #%d\nTên sách: %s\nTrạng thái: %s\nHạn giữ chỗ: %s",
                            r.getId(), r.getBookTitle(), r.getStatus(), r.getExpiryDate());
                    JOptionPane.showMessageDialog(this, msg, "Thành Công", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                },
                (Exception ex) -> {
                    submitButton.setEnabled(true);
                    cancelButton.setEnabled(true);
                    statusLabel.setText("Đặt trước thất bại.");
                    JOptionPane.showMessageDialog(this, "Đặt trước sách thất bại: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
        );
    }

    public boolean isSaved() {
        return saved;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookIdField;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel lblBookId;
    private javax.swing.JLabel lblStudentId;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField studentIdField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
