package thuvien.client.view.dialogs;

import java.awt.Window;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import thuvien.client.controller.ClientStudentController;
import thuvien.client.network.NetworkClient;
import thuvien.client.view.common.AsyncWorker;
import thuvien.common.dto.StudentDTO;
import thuvien.common.enums.StudentStatus;

/**
 * Modal dialog for creating and editing Student records.
 */
public class StudentFormDialog extends JDialog {
    private final ClientStudentController studentController;
    private final StudentDTO studentToEdit;
    private boolean saved = false;

    public StudentFormDialog(Window owner, NetworkClient networkClient, StudentDTO studentToEdit) {
        super(owner, ModalityType.APPLICATION_MODAL);
        this.studentController = new ClientStudentController(networkClient);
        this.studentToEdit = studentToEdit;
        initComponents();
        initCustom();
    }

    private void initCustom() {
        setTitle(studentToEdit == null ? "Thêm Sinh Viên Mới" : "Chỉnh Sửa Sinh Viên (" + studentToEdit.getStudentCode() + ")");
        ((javax.swing.JComponent) getContentPane()).setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        setSize(480, 430);
        setLocationRelativeTo(getOwner());
        getRootPane().setDefaultButton(saveButton);

        if (studentToEdit != null) {
            codeField.setText(studentToEdit.getStudentCode());
            codeField.setEditable(false);
            nameField.setText(studentToEdit.getFullName());
            classField.setText(studentToEdit.getClassName() != null ? studentToEdit.getClassName() : "");
            phoneField.setText(studentToEdit.getPhone() != null ? studentToEdit.getPhone() : "");
            emailField.setText(studentToEdit.getEmail() != null ? studentToEdit.getEmail() : "");
            limitSpinner.setValue(studentToEdit.getMaxBorrowLimit());
            if (studentToEdit.getStatus() != null) {
                statusCombo.setSelectedItem(studentToEdit.getStatus());
            }
            saveButton.setText("Lưu Thay Đổi");
        } else {
            statusCombo.setSelectedItem(StudentStatus.ACTIVE);
            saveButton.setText("Tạo Sinh Viên");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        formPanel = new javax.swing.JPanel();
        lblCode = new javax.swing.JLabel();
        codeField = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        lblClass = new javax.swing.JLabel();
        classField = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        lblLimit = new javax.swing.JLabel();
        limitSpinner = new javax.swing.JSpinner();
        lblStatus = new javax.swing.JLabel();
        statusCombo = new javax.swing.JComboBox<StudentStatus>();
        bottomPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông Tin Sinh Viên");
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        formPanel.setLayout(new java.awt.GridBagLayout());

        lblCode.setText("Mã sinh viên:*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(lblCode, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(codeField, gridBagConstraints);

        lblName.setText("Họ và tên:*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(lblName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(nameField, gridBagConstraints);

        lblClass.setText("Lớp / Khóa:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(lblClass, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(classField, gridBagConstraints);

        lblPhone.setText("Số điện thoại:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(lblPhone, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(phoneField, gridBagConstraints);

        lblEmail.setText("Địa chỉ Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(lblEmail, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(emailField, gridBagConstraints);

        lblLimit.setText("Hạn mức mượn:*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(lblLimit, gridBagConstraints);

        limitSpinner.setModel(new javax.swing.SpinnerNumberModel(5, 1, 20, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(limitSpinner, gridBagConstraints);

        lblStatus.setText("Trạng thái:*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(lblStatus, gridBagConstraints);

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(thuvien.common.enums.StudentStatus.values()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        formPanel.add(statusCombo, gridBagConstraints);

        getContentPane().add(formPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setLayout(new java.awt.BorderLayout(5, 5));

        statusLabel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText(" ");
        bottomPanel.add(statusLabel, java.awt.BorderLayout.NORTH);

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 10, 5));

        cancelButton.setText("Hủy bỏ");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saveButton.setText("Lưu Thay Đổi");
        saveButton.setPreferredSize(new java.awt.Dimension(130, 30));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(saveButton);

        bottomPanel.add(buttonPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(bottomPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        saveStudent();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void saveStudent() {
        String code = codeField.getText().trim();
        String name = nameField.getText().trim();

        if (code.isEmpty() || name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ Mã sinh viên và Họ tên.", "Lỗi Xác Thực", JOptionPane.WARNING_MESSAGE);
            return;
        }

        StudentDTO student = (studentToEdit != null) ? studentToEdit : new StudentDTO();
        student.setStudentCode(code);
        student.setFullName(name);
        student.setClassName(classField.getText().trim());
        student.setPhone(phoneField.getText().trim());
        student.setEmail(emailField.getText().trim());
        student.setMaxBorrowLimit((Integer) limitSpinner.getValue());
        student.setStatus((StudentStatus) statusCombo.getSelectedItem());

        saveButton.setEnabled(false);
        cancelButton.setEnabled(false);
        statusLabel.setText("Đang lưu thông tin sinh viên lên máy chủ...");

        if (studentToEdit == null) {
            // Create
            AsyncWorker.run(
                    () -> studentController.createStudent(student),
                    (Long newId) -> {
                        saved = true;
                        JOptionPane.showMessageDialog(this, "Tạo hồ sơ sinh viên thành công! Mã ID: " + newId, "Thành Công", JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                    },
                    (Exception ex) -> {
                        saveButton.setEnabled(true);
                        cancelButton.setEnabled(true);
                        statusLabel.setText("Lưu thất bại.");
                        JOptionPane.showMessageDialog(this, "Thêm sinh viên thất bại: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
            );
        } else {
            // Update
            AsyncWorker.run(
                    () -> studentController.updateStudent(student),
                    (Boolean ok) -> {
                        saved = true;
                        JOptionPane.showMessageDialog(this, "Cập nhật hồ sơ sinh viên thành công.", "Thành Công", JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                    },
                    (Exception ex) -> {
                        saveButton.setEnabled(true);
                        cancelButton.setEnabled(true);
                        statusLabel.setText("Cập nhật thất bại.");
                        JOptionPane.showMessageDialog(this, "Cập nhật sinh viên thất bại: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
            );
        }
    }

    public boolean isSaved() {
        return saved;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField classField;
    private javax.swing.JTextField codeField;
    private javax.swing.JTextField emailField;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLimit;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JSpinner limitSpinner;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<StudentStatus> statusCombo;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
