package thuvien.client.view.panels;

import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import thuvien.client.controller.ClientAuditLogController;
import thuvien.client.network.NetworkClient;
import thuvien.client.session.ClientSession;
import thuvien.client.view.LoginForm;
import thuvien.client.view.common.AsyncWorker;
import thuvien.common.dto.AuditLogDTO;
import thuvien.common.exception.AuthenticationException;
import thuvien.common.exception.AuthorizationException;

/**
 * Giao diện quản trị xem xét nhật ký hệ thống và sự kiện bảo mật.
 * Giới hạn quyền dành cho Quản trị viên (ADMIN).
 */
public class AuditLogManagementPanel extends JPanel {
    private static final Logger LOGGER = Logger.getLogger(AuditLogManagementPanel.class.getName());
    private static final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

    private final NetworkClient networkClient;
    private final ClientAuditLogController auditLogController;

    private DefaultTableModel tableModel;
    private List<AuditLogDTO> allLogs = new ArrayList<>();
    private Timer pollTimer;
    private boolean isPolling = false;

    public AuditLogManagementPanel(NetworkClient networkClient) {
        this.networkClient = networkClient;
        this.auditLogController = new ClientAuditLogController(networkClient);

        initComponents();
        initCustom();
        loadAuditLogs();
        startAutoRefresh();
    }

    private void initCustom() {
        setBorder(BorderFactory.createEmptyBorder(10, 15, 10, 15));
        topToolbar.setBorder(BorderFactory.createEmptyBorder(0, 0, 10, 0));

        String[] columnNames = {"Mã", "Thời gian", "Người thực hiện", "Hành động", "Đối tượng", "Mã ĐT", "Chi tiết thao tác"};
        tableModel = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        logTable.setModel(tableModel);
        logTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        logTable.setRowHeight(25);
        logTable.getTableHeader().setFont(logTable.getTableHeader().getFont().deriveFont(Font.BOLD));
        logTable.getTableHeader().setReorderingAllowed(false);
        logTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        logTable.getColumnModel().getColumn(1).setPreferredWidth(140);
        logTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        logTable.getColumnModel().getColumn(3).setPreferredWidth(130);
        logTable.getColumnModel().getColumn(4).setPreferredWidth(110);
        logTable.getColumnModel().getColumn(5).setPreferredWidth(70);
        logTable.getColumnModel().getColumn(6).setPreferredWidth(280);

        logTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                displaySelectedLog();
            }
        });

        tableScroll.getViewport().setBackground(Color.WHITE);

        detailCard.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(1, 0, 0, 0, new Color(220, 225, 235)),
                BorderFactory.createEmptyBorder(8, 12, 8, 12)
        ));
        splitPane.setBorder(null);
        statusLabel.setBorder(BorderFactory.createEmptyBorder(6, 4, 2, 4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topToolbar = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        lblLimit = new javax.swing.JLabel();
        limitCombo = new javax.swing.JComboBox<Integer>();
        refreshBtn = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        filterField = new javax.swing.JTextField();
        filterBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        splitPane = new javax.swing.JSplitPane();
        tableScroll = new javax.swing.JScrollPane();
        logTable = new javax.swing.JTable();
        detailCard = new javax.swing.JPanel();
        detailTitle = new javax.swing.JLabel();
        detailGrid = new javax.swing.JPanel();
        pnlDetailId = new javax.swing.JPanel();
        lblDetailId = new javax.swing.JLabel();
        detailIdVal = new javax.swing.JLabel();
        pnlDetailTime = new javax.swing.JPanel();
        lblDetailTime = new javax.swing.JLabel();
        detailTimeVal = new javax.swing.JLabel();
        pnlDetailUser = new javax.swing.JPanel();
        lblDetailUser = new javax.swing.JLabel();
        detailUserVal = new javax.swing.JLabel();
        pnlDetailAction = new javax.swing.JPanel();
        lblDetailAction = new javax.swing.JLabel();
        detailActionVal = new javax.swing.JLabel();
        pnlDetailEntity = new javax.swing.JPanel();
        lblDetailEntity = new javax.swing.JLabel();
        detailEntityVal = new javax.swing.JLabel();
        pnlDetailEntityId = new javax.swing.JPanel();
        lblDetailEntityId = new javax.swing.JLabel();
        detailEntityIdVal = new javax.swing.JLabel();
        pnlDetailNotes = new javax.swing.JPanel();
        lblDetailNotes = new javax.swing.JLabel();
        detailNotesVal = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout(5, 5));

        topToolbar.setOpaque(false);
        topToolbar.setLayout(new java.awt.BorderLayout(10, 0));

        leftPanel.setOpaque(false);
        leftPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 8, 0));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(25, 45, 80));
        titleLabel.setText("Nhật ký Hệ thống & Sự kiện Bảo mật");
        leftPanel.add(titleLabel);

        lblLimit.setText("Số lượng:");
        leftPanel.add(lblLimit);

        limitCombo.setModel(new javax.swing.DefaultComboBoxModel(new Integer[] { 25, 50, 100, 200 }));
        limitCombo.setSelectedItem(50);
        limitCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limitComboActionPerformed(evt);
            }
        });
        leftPanel.add(limitCombo);

        refreshBtn.setText("Làm mới");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        leftPanel.add(refreshBtn);

        topToolbar.add(leftPanel, java.awt.BorderLayout.WEST);

        rightPanel.setOpaque(false);
        rightPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 8, 0));

        lblSearch.setText("Tìm kiếm:");
        rightPanel.add(lblSearch);

        filterField.setColumns(15);
        filterField.setToolTipText("Lọc theo hành động, người dùng, đối tượng hoặc chi tiết...");
        filterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterFieldActionPerformed(evt);
            }
        });
        rightPanel.add(filterField);

        filterBtn.setText("Tìm");
        filterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterBtnActionPerformed(evt);
            }
        });
        rightPanel.add(filterBtn);

        resetBtn.setText("Xóa bộ lọc");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        rightPanel.add(resetBtn);

        topToolbar.add(rightPanel, java.awt.BorderLayout.EAST);

        add(topToolbar, java.awt.BorderLayout.NORTH);

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPane.setResizeWeight(0.72);
        splitPane.setContinuousLayout(true);

        logTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Thời gian", "Người thực hiện", "Hành động", "Đối tượng", "Mã ĐT", "Chi tiết thao tác"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        logTable.setRowHeight(25);
        logTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableScroll.setViewportView(logTable);

        splitPane.setTopComponent(tableScroll);

        detailCard.setBackground(new java.awt.Color(248, 250, 252));
        detailCard.setLayout(new java.awt.BorderLayout(5, 5));

        detailTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        detailTitle.setForeground(new java.awt.Color(50, 60, 75));
        detailTitle.setText("Chi tiết Bản ghi Nhật ký");
        detailCard.add(detailTitle, java.awt.BorderLayout.NORTH);

        detailGrid.setOpaque(false);
        detailGrid.setLayout(new java.awt.GridLayout(4, 2, 10, 4));

        pnlDetailId.setOpaque(false);
        pnlDetailId.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 0));

        lblDetailId.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblDetailId.setForeground(new java.awt.Color(80, 85, 95));
        lblDetailId.setText("Mã nhật ký:");
        pnlDetailId.add(lblDetailId);

        detailIdVal.setText("—");
        pnlDetailId.add(detailIdVal);

        detailGrid.add(pnlDetailId);

        pnlDetailTime.setOpaque(false);
        pnlDetailTime.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 0));

        lblDetailTime.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblDetailTime.setForeground(new java.awt.Color(80, 85, 95));
        lblDetailTime.setText("Thời gian ghi nhận:");
        pnlDetailTime.add(lblDetailTime);

        detailTimeVal.setText("—");
        pnlDetailTime.add(detailTimeVal);

        detailGrid.add(pnlDetailTime);

        pnlDetailUser.setOpaque(false);
        pnlDetailUser.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 0));

        lblDetailUser.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblDetailUser.setForeground(new java.awt.Color(80, 85, 95));
        lblDetailUser.setText("Tài khoản thực hiện:");
        pnlDetailUser.add(lblDetailUser);

        detailUserVal.setText("—");
        pnlDetailUser.add(detailUserVal);

        detailGrid.add(pnlDetailUser);

        pnlDetailAction.setOpaque(false);
        pnlDetailAction.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 0));

        lblDetailAction.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblDetailAction.setForeground(new java.awt.Color(80, 85, 95));
        lblDetailAction.setText("Loại hành động:");
        pnlDetailAction.add(lblDetailAction);

        detailActionVal.setText("—");
        pnlDetailAction.add(detailActionVal);

        detailGrid.add(pnlDetailAction);

        pnlDetailEntity.setOpaque(false);
        pnlDetailEntity.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 0));

        lblDetailEntity.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblDetailEntity.setForeground(new java.awt.Color(80, 85, 95));
        lblDetailEntity.setText("Đối tượng tác động:");
        pnlDetailEntity.add(lblDetailEntity);

        detailEntityVal.setText("—");
        pnlDetailEntity.add(detailEntityVal);

        detailGrid.add(pnlDetailEntity);

        pnlDetailEntityId.setOpaque(false);
        pnlDetailEntityId.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 0));

        lblDetailEntityId.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblDetailEntityId.setForeground(new java.awt.Color(80, 85, 95));
        lblDetailEntityId.setText("Mã đối tượng:");
        pnlDetailEntityId.add(lblDetailEntityId);

        detailEntityIdVal.setText("—");
        pnlDetailEntityId.add(detailEntityIdVal);

        detailGrid.add(pnlDetailEntityId);

        pnlDetailNotes.setOpaque(false);
        pnlDetailNotes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 0));

        lblDetailNotes.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblDetailNotes.setForeground(new java.awt.Color(80, 85, 95));
        lblDetailNotes.setText("Chi tiết thao tác:");
        pnlDetailNotes.add(lblDetailNotes);

        detailNotesVal.setText("—");
        pnlDetailNotes.add(detailNotesVal);

        detailGrid.add(pnlDetailNotes);

        detailCard.add(detailGrid, java.awt.BorderLayout.CENTER);

        splitPane.setBottomComponent(detailCard);

        add(splitPane, java.awt.BorderLayout.CENTER);

        statusLabel.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(110, 115, 125));
        statusLabel.setText("Sẵn sàng.");
        add(statusLabel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void limitComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitComboActionPerformed
        loadAuditLogs();
    }//GEN-LAST:event_limitComboActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        loadAuditLogs();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void filterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterFieldActionPerformed
        applyFilter();
    }//GEN-LAST:event_filterFieldActionPerformed

    private void filterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterBtnActionPerformed
        applyFilter();
    }//GEN-LAST:event_filterBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        filterField.setText("");
        applyFilter();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void startAutoRefresh() {
        pollTimer = new Timer(6000, e -> {
            if (isShowing() && !isPolling) {
                loadSilently();
            }
        });
        pollTimer.start();
    }

    public void loadAuditLogs() {
        int limit = (Integer) limitCombo.getSelectedItem();
        setControlsEnabled(false);
        statusLabel.setText("Đang tải nhật ký hệ thống từ máy chủ...");

        AsyncWorker.run(
                () -> auditLogController.listRecentLogs(limit),
                logs -> {
                    allLogs = logs != null ? logs : new ArrayList<>();
                    applyFilter();
                    setControlsEnabled(true);
                },
                ex -> {
                    setControlsEnabled(true);
                    handleError(ex, "Lỗi tải nhật ký hệ thống");
                }
        );
    }

    private void loadSilently() {
        isPolling = true;
        int limit = (Integer) limitCombo.getSelectedItem();
        AsyncWorker.run(
                () -> auditLogController.listRecentLogs(limit),
                logs -> {
                    isPolling = false;
                    allLogs = logs != null ? logs : new ArrayList<>();
                    applyFilterSilently();
                },
                ex -> isPolling = false
        );
    }

    private void applyFilter() {
        applyFilterInternal(false);
    }

    private void applyFilterSilently() {
        applyFilterInternal(true);
    }

    private void applyFilterInternal(boolean silent) {
        String query = filterField.getText().trim().toLowerCase();

        Long prevSelectedId = null;
        if (silent) {
            int selRow = logTable.getSelectedRow();
            if (selRow >= 0 && selRow < tableModel.getRowCount()) {
                Object val = tableModel.getValueAt(selRow, 0);
                if (val instanceof Long) prevSelectedId = (Long) val;
            }
        }

        tableModel.setRowCount(0);
        int restoreRow = -1;

        List<AuditLogDTO> matched = new ArrayList<>();
        for (AuditLogDTO log : allLogs) {
            if (query.isEmpty()
                    || (log.getAction() != null && log.getAction().toLowerCase().contains(query))
                    || (log.getUsername() != null && log.getUsername().toLowerCase().contains(query))
                    || (log.getEntityName() != null && log.getEntityName().toLowerCase().contains(query))
                    || (log.getDetails() != null && log.getDetails().toLowerCase().contains(query))) {
                matched.add(log);
                tableModel.addRow(new Object[]{
                        log.getId(),
                        log.getCreatedAt() != null ? DATE_FORMAT.format(log.getCreatedAt()) : "N/A",
                        log.getUsername() != null ? log.getUsername() : (log.getUserId() != null ? "User #" + log.getUserId() : "HỆ THỐNG"),
                        log.getAction() != null ? log.getAction() : "—",
                        log.getEntityName() != null ? log.getEntityName() : "—",
                        log.getEntityId() != null ? log.getEntityId() : "—",
                        log.getDetails() != null ? log.getDetails() : "—"
                });

                if (prevSelectedId != null && prevSelectedId.equals(log.getId())) {
                    restoreRow = tableModel.getRowCount() - 1;
                }
            }
        }

        if (restoreRow >= 0 && restoreRow < logTable.getRowCount()) {
            logTable.setRowSelectionInterval(restoreRow, restoreRow);
        }

        if (!silent) {
            if (matched.isEmpty()) {
                statusLabel.setText("Không tìm thấy sự kiện nhật ký nào phù hợp.");
            } else {
                statusLabel.setText("Hiển thị " + matched.size() + " sự kiện nhật ký (Giới hạn: " + limitCombo.getSelectedItem() + ").");
            }
            clearDetail();
        }
    }

    private void displaySelectedLog() {
        int row = logTable.getSelectedRow();
        if (row < 0 || row >= tableModel.getRowCount()) {
            clearDetail();
            return;
        }

        Long id = (Long) tableModel.getValueAt(row, 0);
        AuditLogDTO selected = null;
        for (AuditLogDTO log : allLogs) {
            if (log.getId() != null && log.getId().equals(id)) {
                selected = log;
                break;
            }
        }

        if (selected != null) {
            detailIdVal.setText(String.valueOf(selected.getId()));
            detailTimeVal.setText(selected.getCreatedAt() != null ? DATE_FORMAT.format(selected.getCreatedAt()) : "N/A");
            detailUserVal.setText(selected.getUsername() != null ? selected.getUsername() : "User #" + selected.getUserId());
            detailActionVal.setText(selected.getAction() != null ? selected.getAction() : "—");
            detailEntityVal.setText(selected.getEntityName() != null ? selected.getEntityName() : "—");
            detailEntityIdVal.setText(selected.getEntityId() != null ? String.valueOf(selected.getEntityId()) : "—");
            detailNotesVal.setText(selected.getDetails() != null ? selected.getDetails() : "—");
        } else {
            clearDetail();
        }
    }

    private void clearDetail() {
        detailIdVal.setText("—");
        detailTimeVal.setText("—");
        detailUserVal.setText("—");
        detailActionVal.setText("—");
        detailEntityVal.setText("—");
        detailEntityIdVal.setText("—");
        detailNotesVal.setText("—");
    }

    private void setControlsEnabled(boolean enabled) {
        refreshBtn.setEnabled(enabled);
        limitCombo.setEnabled(enabled);
        filterField.setEnabled(enabled);
    }

    private void handleError(Throwable ex, String title) {
        LOGGER.log(Level.WARNING, title, ex);
        statusLabel.setText("Lỗi: " + ex.getMessage());

        if (ex instanceof AuthenticationException) {
            String msg = "Phiên làm việc đã hết hạn hoặc không hợp lệ. Vui lòng đăng nhập lại.";
            if (ex.getMessage() != null && ex.getMessage().contains("tạm khóa")) {
                msg = "Tài khoản của bạn đang bị tạm khóa do đăng nhập sai quá số lần cho phép. Vui lòng thử lại sau 15 phút.";
            }
            JOptionPane.showMessageDialog(this,
                    msg,
                    "Hết phiên",
                    JOptionPane.WARNING_MESSAGE);
            ClientSession.getInstance().clear();
            networkClient.disconnect();
            java.awt.Window parent = SwingUtilities.getWindowAncestor(this);
            if (parent != null) {
                parent.dispose();
            }
            new LoginForm(networkClient).setVisible(true);
        } else if (ex instanceof AuthorizationException) {
            JOptionPane.showMessageDialog(this,
                    "Từ chối truy cập: Bạn không có quyền xem nhật ký hệ thống.",
                    "Không có quyền",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    title,
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel detailCard;
    private javax.swing.JPanel detailGrid;
    private javax.swing.JLabel detailIdVal;
    private javax.swing.JLabel detailTimeVal;
    private javax.swing.JLabel detailUserVal;
    private javax.swing.JLabel detailActionVal;
    private javax.swing.JLabel detailEntityVal;
    private javax.swing.JLabel detailEntityIdVal;
    private javax.swing.JLabel detailNotesVal;
    private javax.swing.JLabel detailTitle;
    private javax.swing.JButton filterBtn;
    private javax.swing.JTextField filterField;
    private javax.swing.JLabel lblDetailAction;
    private javax.swing.JLabel lblDetailEntity;
    private javax.swing.JLabel lblDetailEntityId;
    private javax.swing.JLabel lblDetailId;
    private javax.swing.JLabel lblDetailNotes;
    private javax.swing.JLabel lblDetailTime;
    private javax.swing.JLabel lblDetailUser;
    private javax.swing.JLabel lblLimit;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JComboBox<Integer> limitCombo;
    private javax.swing.JTable logTable;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel pnlDetailAction;
    private javax.swing.JPanel pnlDetailEntity;
    private javax.swing.JPanel pnlDetailEntityId;
    private javax.swing.JPanel pnlDetailId;
    private javax.swing.JPanel pnlDetailNotes;
    private javax.swing.JPanel pnlDetailTime;
    private javax.swing.JPanel pnlDetailUser;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JScrollPane tableScroll;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel topToolbar;
    // End of variables declaration//GEN-END:variables
}
