package thuvien.client.view.panels;

import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import thuvien.client.controller.ClientBorrowController;
import thuvien.client.controller.ClientSearchSuggestionController;
import thuvien.client.network.NetworkClient;
import thuvien.client.session.ClientSession;
import thuvien.client.view.LoginForm;
import thuvien.client.view.common.AsyncWorker;
import thuvien.client.view.common.SearchAutoCompleteHelper;
import thuvien.client.view.dialogs.BorrowDialog;
import thuvien.common.dto.BorrowRecordDTO;
import thuvien.common.dto.ReturnResultDTO;
import thuvien.common.enums.BorrowStatus;
import thuvien.common.exception.AuthenticationException;
import thuvien.common.exception.AuthorizationException;
import thuvien.common.exception.NetworkException;

/**
 * Panel providing circulation management (Borrow & Return) for staff,
 * and active loans inspection for students.
 */
public class BorrowManagementPanel extends JPanel {
    private static final Logger LOGGER = Logger.getLogger(BorrowManagementPanel.class.getName());
    private static final SimpleDateFormat DATE_FMT = new SimpleDateFormat("yyyy-MM-dd HH:mm");
    private static final SimpleDateFormat TIME_FMT = new SimpleDateFormat("HH:mm:ss");

    private final NetworkClient networkClient;
    private final ClientBorrowController borrowController;
    private final boolean isStaff;

    private DefaultTableModel tableModel;
    private List<BorrowRecordDTO> allRecords = new ArrayList<>();
    private javax.swing.Timer pollTimer;
    private volatile boolean isRefreshing = false;

    public BorrowManagementPanel(NetworkClient networkClient) {
        this.networkClient = networkClient;
        this.borrowController = new ClientBorrowController(networkClient);
        this.isStaff = ClientSession.getInstance().isAdmin() || ClientSession.getInstance().isLibrarian();

        initComponents();
        initCustom();
        loadRecords();
        initAutoRefresh();
    }

    private void initCustom() {
        setBorder(BorderFactory.createEmptyBorder(10, 15, 10, 15));
        topToolbar.setBorder(BorderFactory.createEmptyBorder(0, 0, 10, 0));
        tableScroll.setBorder(BorderFactory.createLineBorder(new Color(220, 225, 230)));
        detailCard.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(1, 0, 0, 0, new Color(220, 225, 230)),
                BorderFactory.createEmptyBorder(10, 15, 10, 15)
        ));
        bottomBar.setBorder(BorderFactory.createEmptyBorder(6, 4, 4, 4));

        if (!isStaff) {
            newBorrowBtn.setVisible(false);
            returnBtn.setVisible(false);
        }

        SearchAutoCompleteHelper.attach(searchField, "BORROW", new ClientSearchSuggestionController(networkClient), () -> applyFilter(false));

        String[] columns = isStaff
                ? new String[]{"Mã Phiếu", "Mã SV", "Tên Sinh Viên", "Tên Sách", "Ngày Mượn", "Hạn Trả", "Ngày Trả", "Trạng Thái"}
                : new String[]{"Mã Phiếu", "Tên Sách", "Mã ISBN", "Ngày Mượn", "Hạn Trả", "Ngày Trả", "Trạng Thái"};

        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };

        recordTable.setModel(tableModel);
        recordTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        recordTable.setRowHeight(24);
        recordTable.getTableHeader().setFont(recordTable.getTableHeader().getFont().deriveFont(Font.BOLD));
        recordTable.setAutoCreateRowSorter(true);

        recordTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                BorrowRecordDTO r = getSelectedRecord();
                if (returnBtn != null) {
                    returnBtn.setEnabled(r != null && (r.getStatus() == BorrowStatus.ACTIVE || r.getStatus() == BorrowStatus.OVERDUE));
                }
                updateDetails(r);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        topToolbar = new javax.swing.JPanel();
        leftControls = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        statusFilterCombo = new javax.swing.JComboBox<String>();
        filterBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        rightControls = new javax.swing.JPanel();
        newBorrowBtn = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();
        splitPane = new javax.swing.JSplitPane();
        tableScroll = new javax.swing.JScrollPane();
        recordTable = new javax.swing.JTable();
        detailCard = new javax.swing.JPanel();
        detailHeader = new javax.swing.JLabel();
        gridDetails = new javax.swing.JPanel();
        lblMpm = new javax.swing.JLabel();
        detailIdVal = new javax.swing.JLabel();
        lblSv = new javax.swing.JLabel();
        detailStudentVal = new javax.swing.JLabel();
        lblSm = new javax.swing.JLabel();
        detailBookVal = new javax.swing.JLabel();
        lblTt = new javax.swing.JLabel();
        detailStatusVal = new javax.swing.JLabel();
        lblNm = new javax.swing.JLabel();
        detailBorrowDateVal = new javax.swing.JLabel();
        lblHt = new javax.swing.JLabel();
        detailDueDateVal = new javax.swing.JLabel();
        lblNttt = new javax.swing.JLabel();
        detailReturnDateVal = new javax.swing.JLabel();
        lblGc = new javax.swing.JLabel();
        detailNotesVal = new javax.swing.JLabel();
        bottomBar = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout(5, 5));

        topToolbar.setOpaque(false);
        topToolbar.setLayout(new java.awt.BorderLayout(10, 0));

        leftControls.setOpaque(false);
        leftControls.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 6, 0));

        lblSearch.setText("Tìm kiếm lượt mượn:");
        leftControls.add(lblSearch);

        searchField.setColumns(13);
        searchField.setToolTipText("Tìm kiếm theo Mã phiếu, Mã SV, Tên SV, Tên sách hoặc ISBN");
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        leftControls.add(searchField);

        statusFilterCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả trạng thái", "Đang mượn (Chưa trả)", "Đã trả", "Quá hạn" }));
        statusFilterCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusFilterComboActionPerformed(evt);
            }
        });
        leftControls.add(statusFilterCombo);

        filterBtn.setText("Tìm");
        filterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterBtnActionPerformed(evt);
            }
        });
        leftControls.add(filterBtn);

        resetBtn.setText("Xóa bộ lọc");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        leftControls.add(resetBtn);

        refreshBtn.setText("Làm mới");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        leftControls.add(refreshBtn);

        topToolbar.add(leftControls, java.awt.BorderLayout.WEST);

        rightControls.setOpaque(false);
        rightControls.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 6, 0));

        newBorrowBtn.setBackground(new java.awt.Color(230, 245, 230));
        newBorrowBtn.setText("Lập Phiếu Mượn");
        newBorrowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBorrowBtnActionPerformed(evt);
            }
        });
        rightControls.add(newBorrowBtn);

        returnBtn.setBackground(new java.awt.Color(230, 240, 255));
        returnBtn.setText("Nhận Trả Sách");
        returnBtn.setEnabled(false);
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        rightControls.add(returnBtn);

        topToolbar.add(rightControls, java.awt.BorderLayout.EAST);

        add(topToolbar, java.awt.BorderLayout.NORTH);

        splitPane.setDividerSize(6);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPane.setResizeWeight(0.65);

        recordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phiếu", "Mã SV", "Tên Sinh Viên", "Tên Sách", "Ngày Mượn", "Hạn Trả", "Ngày Trả", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        recordTable.setAutoCreateRowSorter(true);
        recordTable.setRowHeight(24);
        recordTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableScroll.setViewportView(recordTable);

        splitPane.setTopComponent(tableScroll);

        detailCard.setBackground(new java.awt.Color(248, 250, 252));
        detailCard.setLayout(new java.awt.BorderLayout(10, 10));

        detailHeader.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        detailHeader.setText("Thông Tin Chi Tiết Lượt Mượn Được Chọn");
        detailCard.add(detailHeader, java.awt.BorderLayout.NORTH);

        gridDetails.setOpaque(false);
        gridDetails.setLayout(new java.awt.GridBagLayout());

        lblMpm.setText("Mã phiếu mượn:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        gridDetails.add(lblMpm, gridBagConstraints);

        detailIdVal.setText("Chưa chọn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        gridDetails.add(detailIdVal, gridBagConstraints);

        lblSv.setText("Sinh viên:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        gridDetails.add(lblSv, gridBagConstraints);

        detailStudentVal.setText("Chưa chọn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        gridDetails.add(detailStudentVal, gridBagConstraints);

        lblSm.setText("Sách mượn:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        gridDetails.add(lblSm, gridBagConstraints);

        detailBookVal.setText("Chưa chọn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        gridDetails.add(detailBookVal, gridBagConstraints);

        lblTt.setText("Trạng thái:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        gridDetails.add(lblTt, gridBagConstraints);

        detailStatusVal.setText("Chưa chọn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        gridDetails.add(detailStatusVal, gridBagConstraints);

        lblNm.setText("Ngày mượn:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        gridDetails.add(lblNm, gridBagConstraints);

        detailBorrowDateVal.setText("Chưa chọn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        gridDetails.add(detailBorrowDateVal, gridBagConstraints);

        lblHt.setText("Hạn trả:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        gridDetails.add(lblHt, gridBagConstraints);

        detailDueDateVal.setText("Chưa chọn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        gridDetails.add(detailDueDateVal, gridBagConstraints);

        lblNttt.setText("Ngày trả thực tế:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        gridDetails.add(lblNttt, gridBagConstraints);

        detailReturnDateVal.setText("Chưa chọn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        gridDetails.add(detailReturnDateVal, gridBagConstraints);

        lblGc.setText("Ghi chú:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        gridDetails.add(lblGc, gridBagConstraints);

        detailNotesVal.setText("Chưa chọn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 8, 3, 8);
        gridDetails.add(detailNotesVal, gridBagConstraints);

        detailCard.add(gridDetails, java.awt.BorderLayout.CENTER);

        splitPane.setBottomComponent(detailCard);

        add(splitPane, java.awt.BorderLayout.CENTER);

        bottomBar.setOpaque(false);
        bottomBar.setLayout(new java.awt.BorderLayout());

        statusLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        statusLabel.setText("Sẵn sàng");
        bottomBar.add(statusLabel, java.awt.BorderLayout.WEST);

        add(bottomBar, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        applyFilter(false);
    }//GEN-LAST:event_searchFieldActionPerformed

    private void statusFilterComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusFilterComboActionPerformed
        applyFilter(false);
    }//GEN-LAST:event_statusFilterComboActionPerformed

    private void filterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterBtnActionPerformed
        applyFilter(false);
    }//GEN-LAST:event_filterBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        searchField.setText("");
        statusFilterCombo.setSelectedIndex(0);
        applyFilter(false);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        loadRecords();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void newBorrowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBorrowBtnActionPerformed
        openBorrowDialog();
    }//GEN-LAST:event_newBorrowBtnActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        performReturn();
    }//GEN-LAST:event_returnBtnActionPerformed

    private void initAutoRefresh() {
        pollTimer = new javax.swing.Timer(6000, e -> {
            if (isShowing() && isDisplayable() && !isRefreshing) {
                loadRecordsSilently();
            }
        });
        addAncestorListener(new javax.swing.event.AncestorListener() {
            @Override
            public void ancestorAdded(javax.swing.event.AncestorEvent event) {
                if (pollTimer != null && !pollTimer.isRunning()) {
                    pollTimer.start();
                }
            }
            @Override
            public void ancestorRemoved(javax.swing.event.AncestorEvent event) {
                if (pollTimer != null && pollTimer.isRunning()) {
                    pollTimer.stop();
                }
            }
            @Override
            public void ancestorMoved(javax.swing.event.AncestorEvent event) {}
        });
    }

    public void loadRecords() {
        if (isRefreshing) return;
        isRefreshing = true;
        refreshBtn.setEnabled(false);
        statusLabel.setText("Đang tải dữ liệu mượn trả từ máy chủ...");

        AsyncWorker.run(
                () -> isStaff ? borrowController.listAllBorrowRecords() : borrowController.getMyActiveLoans(),
                (List<BorrowRecordDTO> records) -> {
                    isRefreshing = false;
                    refreshBtn.setEnabled(true);
                    allRecords = records != null ? records : new ArrayList<>();
                    applyFilter(false);
                },
                (Exception ex) -> {
                    isRefreshing = false;
                    refreshBtn.setEnabled(true);
                    handleError(ex);
                }
        );
    }

    private void loadRecordsSilently() {
        if (isRefreshing) return;
        isRefreshing = true;

        AsyncWorker.run(
                () -> isStaff ? borrowController.listAllBorrowRecords() : borrowController.getMyActiveLoans(),
                (List<BorrowRecordDTO> records) -> {
                    isRefreshing = false;
                    allRecords = records != null ? records : new ArrayList<>();
                    applyFilter(true);
                },
                (Exception ex) -> {
                    isRefreshing = false;
                }
        );
    }

    private void applyFilter(boolean silent) {
        Long selectedId = null;
        BorrowRecordDTO prev = getSelectedRecord();
        if (prev != null) selectedId = prev.getId();

        String kw = searchField.getText().trim().toLowerCase();
        int statusIdx = statusFilterCombo.getSelectedIndex();

        tableModel.setRowCount(0);
        int count = 0;
        int restoreRow = -1;

        for (BorrowRecordDTO r : allRecords) {
            // Status filter
            if (statusIdx == 1 && (r.getStatus() != BorrowStatus.ACTIVE && r.getStatus() != BorrowStatus.OVERDUE)) continue;
            if (statusIdx == 2 && r.getStatus() != BorrowStatus.RETURNED) continue;
            if (statusIdx == 3 && r.getStatus() != BorrowStatus.OVERDUE) continue;

            // Search filter (ID, StudentCode, StudentName, BookTitle, ISBN)
            if (!kw.isEmpty()) {
                String idStr = r.getId() != null ? r.getId().toString() : "";
                String sc = r.getStudentCode() != null ? r.getStudentCode().toLowerCase() : "";
                String sn = r.getStudentName() != null ? r.getStudentName().toLowerCase() : "";
                String bt = r.getBookTitle() != null ? r.getBookTitle().toLowerCase() : "";
                String isbn = r.getBookIsbn() != null ? r.getBookIsbn().toLowerCase() : "";

                if (!idStr.contains(kw) && !sc.contains(kw) && !sn.contains(kw) && !bt.contains(kw) && !isbn.contains(kw)) {
                    continue;
                }
            }

            if (selectedId != null && selectedId.equals(r.getId())) {
                restoreRow = count;
            }

            if (isStaff) {
                tableModel.addRow(new Object[]{
                        r.getId(),
                        r.getStudentCode(),
                        r.getStudentName(),
                        r.getBookTitle(),
                        r.getBorrowDate() != null ? DATE_FMT.format(r.getBorrowDate()) : "",
                        r.getDueDate() != null ? DATE_FMT.format(r.getDueDate()) : "",
                        r.getReturnDate() != null ? DATE_FMT.format(r.getReturnDate()) : "Chưa trả",
                        mapBorrowStatus(r.getStatus())
                });
            } else {
                tableModel.addRow(new Object[]{
                        r.getId(),
                        r.getBookTitle(),
                        r.getBookIsbn(),
                        r.getBorrowDate() != null ? DATE_FMT.format(r.getBorrowDate()) : "",
                        r.getDueDate() != null ? DATE_FMT.format(r.getDueDate()) : "",
                        r.getReturnDate() != null ? DATE_FMT.format(r.getReturnDate()) : "Chưa trả",
                        mapBorrowStatus(r.getStatus())
                });
            }
            count++;
        }

        if (restoreRow != -1) {
            int viewRow = recordTable.convertRowIndexToView(restoreRow);
            recordTable.setRowSelectionInterval(viewRow, viewRow);
            updateDetails(getSelectedRecord());
        } else if (!silent) {
            clearDetails();
        }

        if (count == 0) {
            statusLabel.setText("Không tìm thấy lượt mượn nào phù hợp.");
        } else {
            statusLabel.setText(String.format("Đã tải %d lượt mượn lúc %s", count, TIME_FMT.format(new Date())));
        }
    }

    private String mapBorrowStatus(BorrowStatus status) {
        if (status == null) return "Chưa rõ";
        switch (status) {
            case ACTIVE: return "Đang mượn";
            case RETURNED: return "Đã trả";
            case OVERDUE: return "Quá hạn";
            case LOST: return "Mất sách";
            default: return status.name();
        }
    }

    private BorrowRecordDTO getSelectedRecord() {
        int row = recordTable.getSelectedRow();
        if (row == -1) return null;
        int modelRow = recordTable.convertRowIndexToModel(row);
        Object idObj = tableModel.getValueAt(modelRow, 0);
        if (idObj instanceof Long) {
            long targetId = (Long) idObj;
            for (BorrowRecordDTO r : allRecords) {
                if (r.getId().equals(targetId)) {
                    return r;
                }
            }
        }
        return null;
    }

    private void updateDetails(BorrowRecordDTO r) {
        if (r == null) {
            clearDetails();
            return;
        }

        detailIdVal.setText(r.getId().toString());
        detailStudentVal.setText(String.format("%s (Mã SV: %s, ID: %d)", r.getStudentName(), r.getStudentCode(), r.getStudentId()));
        detailBookVal.setText(String.format("%s (Mã sách: %d, ISBN: %s)", r.getBookTitle(), r.getBookId(), r.getBookIsbn()));
        detailBorrowDateVal.setText(r.getBorrowDate() != null ? DATE_FMT.format(r.getBorrowDate()) : "N/A");
        detailDueDateVal.setText(r.getDueDate() != null ? DATE_FMT.format(r.getDueDate()) : "N/A");
        detailReturnDateVal.setText(r.getReturnDate() != null ? DATE_FMT.format(r.getReturnDate()) : "Chưa trả");
        detailStatusVal.setText(mapBorrowStatus(r.getStatus()));
        detailNotesVal.setText(r.getNotes() != null && !r.getNotes().isEmpty() ? r.getNotes() : "Không có");
    }

    private void clearDetails() {
        detailIdVal.setText("Chưa chọn");
        detailStudentVal.setText("Chưa chọn");
        detailBookVal.setText("Chưa chọn");
        detailBorrowDateVal.setText("Chưa chọn");
        detailDueDateVal.setText("Chưa chọn");
        detailReturnDateVal.setText("Chưa chọn");
        detailStatusVal.setText("Chưa chọn");
        detailNotesVal.setText("Chưa chọn");
    }

    private void openBorrowDialog() {
        java.awt.Window owner = SwingUtilities.getWindowAncestor(this);
        BorrowDialog dialog = new BorrowDialog(owner, networkClient, null, null);
        dialog.setVisible(true);
        if (dialog.isSaved()) {
            loadRecords();
        }
    }

    private void performReturn() {
        BorrowRecordDTO record = getSelectedRecord();
        if (record == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một lượt mượn cần trả sách.", "Yêu Cầu Chọn", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                String.format("Xác nhận nhận trả sách:\n'%s'\nSinh viên: %s (%s)\n\nTiến hành trả sách ngay bây giờ?",
                        record.getBookTitle(), record.getStudentName(), record.getStudentCode()),
                "Xác Nhận Trả Sách",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
            refreshBtn.setEnabled(false);
            returnBtn.setEnabled(false);
            statusLabel.setText("Đang xử lý trả sách trên máy chủ...");

            AsyncWorker.run(
                    () -> borrowController.returnBook(record.getStudentId(), record.getBookId()),
                    (ReturnResultDTO res) -> {
                        refreshBtn.setEnabled(true);
                        String alertMsg = res.getMessage();
                        if (res.isOverdue()) {
                            alertMsg += String.format("\n\nLƯU Ý: Sách đã bị quá hạn %d ngày!\nHệ thống đã tự động tạo khoản phạt %s VNĐ.",
                                    res.getOverdueDays(), res.getFineAmount());
                            JOptionPane.showMessageDialog(this, alertMsg, "Trả Sách Quá Hạn - Phát Sinh Phạt", JOptionPane.WARNING_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(this, "Nhận trả sách thành công!", "Hoàn Tất Trả Sách", JOptionPane.INFORMATION_MESSAGE);
                        }
                        loadRecords();
                    },
                    this::handleError
            );
        }
    }

    private void handleError(Exception ex) {
        refreshBtn.setEnabled(true);
        if (newBorrowBtn != null) newBorrowBtn.setEnabled(true);
        statusLabel.setText("Lỗi: " + ex.getMessage());
        LOGGER.log(Level.WARNING, "Borrow/Return error", ex);

        if (ex instanceof AuthenticationException) {
            String msg = "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.";
            if (ex.getMessage() != null && ex.getMessage().contains("tạm khóa")) {
                msg = "Tài khoản của bạn đang bị tạm khóa do đăng nhập sai quá số lần cho phép. Vui lòng thử lại sau 15 phút.";
            }
            JOptionPane.showMessageDialog(this, msg, "Hết Hạn Phiên", JOptionPane.ERROR_MESSAGE);
            java.awt.Window win = SwingUtilities.getWindowAncestor(this);
            if (win != null) win.dispose();
            SwingUtilities.invokeLater(() -> new LoginForm(networkClient).setVisible(true));
        } else if (ex instanceof AuthorizationException) {
            JOptionPane.showMessageDialog(this, "Từ chối quyền truy cập: " + ex.getMessage(), "Lỗi Phân Quyền", JOptionPane.ERROR_MESSAGE);
        } else if (ex instanceof NetworkException) {
            JOptionPane.showMessageDialog(this, "Lỗi kết nối máy chủ: " + ex.getMessage(), "Lỗi Mạng", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Lỗi Mượn Trả", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomBar;
    private javax.swing.JLabel detailBookVal;
    private javax.swing.JLabel detailBorrowDateVal;
    private javax.swing.JPanel detailCard;
    private javax.swing.JLabel detailDueDateVal;
    private javax.swing.JLabel detailHeader;
    private javax.swing.JLabel detailIdVal;
    private javax.swing.JLabel detailNotesVal;
    private javax.swing.JLabel detailReturnDateVal;
    private javax.swing.JLabel detailStatusVal;
    private javax.swing.JLabel detailStudentVal;
    private javax.swing.JButton filterBtn;
    private javax.swing.JPanel gridDetails;
    private javax.swing.JLabel lblGc;
    private javax.swing.JLabel lblHt;
    private javax.swing.JLabel lblMpm;
    private javax.swing.JLabel lblNm;
    private javax.swing.JLabel lblNttt;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSm;
    private javax.swing.JLabel lblSv;
    private javax.swing.JLabel lblTt;
    private javax.swing.JPanel leftControls;
    private javax.swing.JButton newBorrowBtn;
    private javax.swing.JTable recordTable;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton returnBtn;
    private javax.swing.JPanel rightControls;
    private javax.swing.JTextField searchField;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JComboBox<String> statusFilterCombo;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JScrollPane tableScroll;
    private javax.swing.JPanel topToolbar;
    // End of variables declaration//GEN-END:variables
}
