package thuvien.client.view.panels;

import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import thuvien.client.controller.ClientReservationController;
import thuvien.client.controller.ClientSearchSuggestionController;
import thuvien.client.network.NetworkClient;
import thuvien.client.session.ClientSession;
import thuvien.client.view.LoginForm;
import thuvien.client.view.common.AsyncWorker;
import thuvien.client.view.common.SearchAutoCompleteHelper;
import thuvien.client.view.dialogs.ReservationDialog;
import thuvien.common.dto.ReservationDTO;
import thuvien.common.enums.ReservationStatus;
import thuvien.common.exception.AuthenticationException;
import thuvien.common.exception.AuthorizationException;
import thuvien.common.exception.NetworkException;

/**
 * Giao diện quản lý và theo dõi đặt trước sách (Reservations / Holds).
 */
public class ReservationManagementPanel extends JPanel {
    private static final Logger LOGGER = Logger.getLogger(ReservationManagementPanel.class.getName());
    private static final SimpleDateFormat DATE_FMT = new SimpleDateFormat("yyyy-MM-dd HH:mm");

    private final NetworkClient networkClient;
    private final ClientReservationController reservationController;
    private final boolean isStaff;

    private DefaultTableModel tableModel;
    private List<ReservationDTO> allReservations = new ArrayList<>();
    private List<ReservationDTO> currentFiltered = new ArrayList<>();
    private Timer pollTimer;
    private boolean isPolling = false;

    public ReservationManagementPanel(NetworkClient networkClient) {
        this.networkClient = networkClient;
        this.reservationController = new ClientReservationController(networkClient);
        this.isStaff = ClientSession.getInstance().isAdmin() || ClientSession.getInstance().isLibrarian();

        initComponents();
        initCustom();
        loadReservations();
        startAutoRefresh();
    }

    private void initCustom() {
        setBorder(BorderFactory.createEmptyBorder(10, 15, 10, 15));
        filterBar.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(230, 235, 240)));
        tableScroll.setBorder(BorderFactory.createLineBorder(new Color(220, 225, 230)));
        bottomBar.setBorder(BorderFactory.createEmptyBorder(6, 4, 4, 4));

        titleLabel.setText(isStaff ? "Quản lý Đặt trước sách" : "Sách tôi đã đặt trước");

        SearchAutoCompleteHelper.attach(searchField, "RESERVATION", new ClientSearchSuggestionController(networkClient), this::applyFilter);

        String[] columns = isStaff
                ? new String[]{"Mã ĐT", "Mã SV", "Tên sinh viên", "Tên sách", "Ngày đặt", "Hạn giữ", "Trạng thái"}
                : new String[]{"Mã ĐT", "Tên sách", "Ngày đặt", "Hạn giữ", "Trạng thái"};

        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };

        reservationTable.setModel(tableModel);
        reservationTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        reservationTable.setRowHeight(25);
        reservationTable.getTableHeader().setFont(reservationTable.getTableHeader().getFont().deriveFont(Font.BOLD));
        reservationTable.setAutoCreateRowSorter(true);

        reservationTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                ReservationDTO selected = getSelectedReservation();
                cancelResBtn.setEnabled(selected != null && selected.getStatus() == ReservationStatus.PENDING);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        northPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        rightBtns = new javax.swing.JPanel();
        newResBtn = new javax.swing.JButton();
        cancelResBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        filterBar = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        statusFilterCombo = new javax.swing.JComboBox<String>();
        searchBtn = new javax.swing.JButton();
        clearFilterBtn = new javax.swing.JButton();
        tableScroll = new javax.swing.JScrollPane();
        reservationTable = new javax.swing.JTable();
        bottomBar = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout(5, 5));

        northPanel.setOpaque(false);
        northPanel.setLayout(new java.awt.BorderLayout(5, 8));

        headerPanel.setOpaque(false);
        headerPanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(25, 45, 80));
        titleLabel.setText("Quản lý Đặt trước sách");
        headerPanel.add(titleLabel, java.awt.BorderLayout.WEST);

        rightBtns.setOpaque(false);
        rightBtns.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 6, 0));

        newResBtn.setBackground(new java.awt.Color(225, 245, 230));
        newResBtn.setText("+ Đặt trước sách");
        newResBtn.setToolTipText("Tạo yêu cầu đặt trước sách mới");
        newResBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newResBtnActionPerformed(evt);
            }
        });
        rightBtns.add(newResBtn);

        cancelResBtn.setBackground(new java.awt.Color(255, 235, 235));
        cancelResBtn.setText("Hủy đặt trước");
        cancelResBtn.setToolTipText("Hủy yêu cầu đặt trước đã chọn");
        cancelResBtn.setEnabled(false);
        cancelResBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelResBtnActionPerformed(evt);
            }
        });
        rightBtns.add(cancelResBtn);

        refreshBtn.setText("Làm mới");
        refreshBtn.setToolTipText("Tải lại danh sách từ máy chủ");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        rightBtns.add(refreshBtn);

        headerPanel.add(rightBtns, java.awt.BorderLayout.EAST);

        northPanel.add(headerPanel, java.awt.BorderLayout.NORTH);

        filterBar.setOpaque(false);
        filterBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 8, 4));

        lblSearch.setText("Tìm kiếm:");
        filterBar.add(lblSearch);

        searchField.setColumns(20);
        searchField.setToolTipText("Tìm theo Mã ĐT, Mã SV, Tên sinh viên, Tên sách...");
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        filterBar.add(searchField);

        lblStatus.setText("Trạng thái:");
        filterBar.add(lblStatus);

        statusFilterCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tất cả trạng thái", "Đang chờ (PENDING)", "Đã hoàn thành (FULFILLED)", "Đã hủy (CANCELLED)" }));
        statusFilterCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusFilterComboActionPerformed(evt);
            }
        });
        filterBar.add(statusFilterCombo);

        searchBtn.setText("Tìm");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        filterBar.add(searchBtn);

        clearFilterBtn.setText("Xóa bộ lọc");
        clearFilterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFilterBtnActionPerformed(evt);
            }
        });
        filterBar.add(clearFilterBtn);

        northPanel.add(filterBar, java.awt.BorderLayout.SOUTH);

        add(northPanel, java.awt.BorderLayout.NORTH);

        reservationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã ĐT", "Mã SV", "Tên sinh viên", "Tên sách", "Ngày đặt", "Hạn giữ", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reservationTable.setAutoCreateRowSorter(true);
        reservationTable.setRowHeight(25);
        reservationTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableScroll.setViewportView(reservationTable);

        add(tableScroll, java.awt.BorderLayout.CENTER);

        bottomBar.setOpaque(false);
        bottomBar.setLayout(new java.awt.BorderLayout());

        statusLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        statusLabel.setText("Sẵn sàng");
        bottomBar.add(statusLabel, java.awt.BorderLayout.WEST);

        add(bottomBar, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void newResBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newResBtnActionPerformed
        openReservationDialog();
    }//GEN-LAST:event_newResBtnActionPerformed

    private void cancelResBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelResBtnActionPerformed
        cancelSelectedReservation();
    }//GEN-LAST:event_cancelResBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        loadReservations();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        applyFilter();
    }//GEN-LAST:event_searchFieldActionPerformed

    private void statusFilterComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusFilterComboActionPerformed
        applyFilter();
    }//GEN-LAST:event_statusFilterComboActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        applyFilter();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void clearFilterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFilterBtnActionPerformed
        resetFilter();
    }//GEN-LAST:event_clearFilterBtnActionPerformed

    private void startAutoRefresh() {
        pollTimer = new Timer(6000, e -> {
            if (isShowing() && !isPolling) {
                loadSilently();
            }
        });
        pollTimer.start();
    }

    public void loadReservations() {
        refreshBtn.setEnabled(false);
        newResBtn.setEnabled(false);
        cancelResBtn.setEnabled(false);
        statusLabel.setText("Đang tải danh sách đặt trước từ máy chủ...");

        if (isStaff) {
            AsyncWorker.run(
                    reservationController::listAllReservations,
                    this::onLoaded,
                    this::handleError
            );
        } else {
            AsyncWorker.run(
                    () -> reservationController.listStudentReservations(null),
                    this::onLoaded,
                    this::handleError
            );
        }
    }

    private void loadSilently() {
        isPolling = true;
        if (isStaff) {
            AsyncWorker.run(
                    reservationController::listAllReservations,
                    list -> {
                        isPolling = false;
                        allReservations = (list != null) ? list : new ArrayList<>();
                        applyFilterSilently();
                    },
                    ex -> isPolling = false
            );
        } else {
            AsyncWorker.run(
                    () -> reservationController.listStudentReservations(null),
                    list -> {
                        isPolling = false;
                        allReservations = (list != null) ? list : new ArrayList<>();
                        applyFilterSilently();
                    },
                    ex -> isPolling = false
            );
        }
    }

    private void onLoaded(List<ReservationDTO> list) {
        refreshBtn.setEnabled(true);
        newResBtn.setEnabled(true);
        allReservations = (list != null) ? list : new ArrayList<>();
        applyFilter();
    }

    private void applyFilter() {
        applyFilterInternal(false);
    }

    private void applyFilterSilently() {
        applyFilterInternal(true);
    }

    private void applyFilterInternal(boolean silent) {
        String kw = searchField.getText().trim().toLowerCase();
        int statusIdx = statusFilterCombo.getSelectedIndex();

        currentFiltered = new ArrayList<>();
        for (ReservationDTO r : allReservations) {
            // Status check
            if (statusIdx == 1 && r.getStatus() != ReservationStatus.PENDING) continue;
            if (statusIdx == 2 && r.getStatus() != ReservationStatus.FULFILLED) continue;
            if (statusIdx == 3 && r.getStatus() != ReservationStatus.CANCELLED) continue;

            // Keyword check
            if (!kw.isEmpty()) {
                boolean match = false;
                if (r.getId() != null && String.valueOf(r.getId()).contains(kw)) match = true;
                if (!match && r.getStudentId() != null && String.valueOf(r.getStudentId()).contains(kw)) match = true;
                if (!match && r.getStudentName() != null && r.getStudentName().toLowerCase().contains(kw)) match = true;
                if (!match && r.getBookTitle() != null && r.getBookTitle().toLowerCase().contains(kw)) match = true;
                if (!match) continue;
            }
            currentFiltered.add(r);
        }

        Long prevSelectedId = null;
        if (silent) {
            ReservationDTO prev = getSelectedReservation();
            if (prev != null) prevSelectedId = prev.getId();
        }

        tableModel.setRowCount(0);
        int restoreRow = -1;

        for (int i = 0; i < currentFiltered.size(); i++) {
            ReservationDTO r = currentFiltered.get(i);
            String resDt = r.getReservationDate() != null ? DATE_FMT.format(r.getReservationDate()) : "";
            String expDt = r.getExpiryDate() != null ? DATE_FMT.format(r.getExpiryDate()) : "";
            String st = formatStatus(r.getStatus());

            if (isStaff) {
                tableModel.addRow(new Object[]{
                        r.getId(),
                        r.getStudentId(),
                        r.getStudentName() != null ? r.getStudentName() : ("ID: " + r.getStudentId()),
                        r.getBookTitle(),
                        resDt,
                        expDt,
                        st
                });
            } else {
                tableModel.addRow(new Object[]{
                        r.getId(),
                        r.getBookTitle(),
                        resDt,
                        expDt,
                        st
                });
            }

            if (prevSelectedId != null && prevSelectedId.equals(r.getId())) {
                restoreRow = i;
            }
        }

        if (restoreRow >= 0 && restoreRow < reservationTable.getRowCount()) {
            reservationTable.setRowSelectionInterval(restoreRow, restoreRow);
        }

        if (!silent) {
            if (currentFiltered.isEmpty()) {
                statusLabel.setText("Không tìm thấy lượt đặt trước nào phù hợp.");
            } else {
                statusLabel.setText(String.format("Đã tải %d lượt đặt trước.", currentFiltered.size()));
            }
        }
    }

    private void resetFilter() {
        searchField.setText("");
        statusFilterCombo.setSelectedIndex(0);
        applyFilter();
    }

    private String formatStatus(ReservationStatus s) {
        if (s == null) return "";
        switch (s) {
            case PENDING:
                return "Đang chờ";
            case FULFILLED:
                return "Đã hoàn thành";
            case CANCELLED:
                return "Đã hủy";
            default:
                return s.name();
        }
    }

    private ReservationDTO getSelectedReservation() {
        int row = reservationTable.getSelectedRow();
        if (row == -1) return null;
        int modelRow = reservationTable.convertRowIndexToModel(row);
        Object idObj = tableModel.getValueAt(modelRow, 0);
        if (idObj instanceof Long) {
            long targetId = (Long) idObj;
            for (ReservationDTO r : currentFiltered) {
                if (r.getId().equals(targetId)) {
                    return r;
                }
            }
        }
        return null;
    }

    private void openReservationDialog() {
        java.awt.Window owner = SwingUtilities.getWindowAncestor(this);
        ReservationDialog dialog = new ReservationDialog(owner, networkClient, null, null);
        dialog.setVisible(true);
        if (dialog.isSaved()) {
            loadReservations();
        }
    }

    private void cancelSelectedReservation() {
        ReservationDTO r = getSelectedReservation();
        if (r == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một lượt đặt trước để hủy.", "Chưa chọn dữ liệu", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                String.format("Bạn có chắc chắn muốn hủy lượt đặt trước #%d cho sách:\n'%s' không?", r.getId(), r.getBookTitle()),
                "Xác nhận hủy đặt trước",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
            refreshBtn.setEnabled(false);
            cancelResBtn.setEnabled(false);
            statusLabel.setText("Đang xử lý hủy đặt trước trên máy chủ...");

            AsyncWorker.run(
                    () -> reservationController.cancelReservation(r.getId()),
                    (Boolean ok) -> {
                        refreshBtn.setEnabled(true);
                        JOptionPane.showMessageDialog(this, "Hủy đặt trước thành công.", "Đã hủy", JOptionPane.INFORMATION_MESSAGE);
                        loadReservations();
                    },
                    this::handleError
            );
        }
    }

    private void handleError(Exception ex) {
        refreshBtn.setEnabled(true);
        newResBtn.setEnabled(true);
        statusLabel.setText("Lỗi: " + ex.getMessage());
        LOGGER.log(Level.WARNING, "Reservation error", ex);

        if (ex instanceof AuthenticationException) {
            String msg = "Phiên làm việc đã hết hạn. Vui lòng đăng nhập lại.";
            if (ex.getMessage() != null && ex.getMessage().contains("tạm khóa")) {
                msg = "Tài khoản của bạn đang bị tạm khóa do đăng nhập sai quá số lần cho phép. Vui lòng thử lại sau 15 phút.";
            }
            JOptionPane.showMessageDialog(this, msg, "Hết phiên", JOptionPane.ERROR_MESSAGE);
            java.awt.Window win = SwingUtilities.getWindowAncestor(this);
            if (win != null) win.dispose();
            SwingUtilities.invokeLater(() -> new LoginForm(networkClient).setVisible(true));
        } else if (ex instanceof AuthorizationException) {
            JOptionPane.showMessageDialog(this, "Từ chối truy cập: " + ex.getMessage(), "Không có quyền", JOptionPane.ERROR_MESSAGE);
        } else if (ex instanceof NetworkException) {
            JOptionPane.showMessageDialog(this, "Lỗi kết nối máy chủ: " + ex.getMessage(), "Lỗi kết nối", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Thao tác thất bại: " + ex.getMessage(), "Lỗi đặt trước", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomBar;
    private javax.swing.JButton cancelResBtn;
    private javax.swing.JButton clearFilterBtn;
    private javax.swing.JPanel filterBar;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JButton newResBtn;
    private javax.swing.JPanel northPanel;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTable reservationTable;
    private javax.swing.JPanel rightBtns;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JComboBox<String> statusFilterCombo;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JScrollPane tableScroll;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
